### ISSUE TITLE
Earning from MPH is about half what MPM expects.. is it normal?

### ISSUE THREAD

**Issue by sepa85** [MultiPoolMiner/MultiPoolMiner#1011]
Hi guys, I have a problem with a discrepancy between the MultiPoolMiner expected income and the real balance in MiningPoolHub (auto exchange in Ethereum).

At the moment I have only a GTX 1080, but I'm planning to make a couple of rigs. MPM says that the income should be something like 0.00057 BTC ±20 % (0.00047-0.00068), but the balance registered in MPH is a lot less, 0.003717 ETH (about 0.00031 BTC) in the last 24 hours, and almost the same in the last two days.

I was using the standard algos plus skein and eth, CcminerLyraRE2, CcminerLyra2Z disabled and switching prevention equal to 3.

The suspects (and possible solution?):
- fluctuation of the coins prices (choose less algos)
- too much switch (change switching prevention)
- the pool steal/do something wrong with the profit (change pool)
- it's just normal (in this case my experience with Nicehash is overall better)

I attach the last part of the log to reference.

I hope this can help someone else.. ;)

[2018-01-09_15-13-15.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1624664/2018-01-09_15-13-15.txt)

**Comment by komer83** [comment]
You need to wait for all auto exchanges to complete, it can take minutes and it can take days. That's the only real issue I found with MPH, same goes to Zpool too, after a 24 period I made the minimum for deposit, three days after I still had coins of validation and exchange.

**Comment by cmbconcretefire** [comment]
Yeah well, until NH returns my btc like they say they will.....I will use other miners or mine a coin directly. I actually do believe NH will return / repay the money that was stolen, but until they do, I won't use them. Bite me once? Shame on you. Bite me twice? It won't be pleasant. :) 

Only thing I can throw in here is that it is recommended to ONLY use miningpoolhub < in your bat file. It is specifically NOT recommended to use miningpoolhubcoins. Apparently someone has done the math and by using miningpoolhub only, you get penalized less for jumping around. And that means more $ in your pocket.

**Comment by komer83** [comment]
Can you link that math?

**Comment by cmbconcretefire** [comment]
No. But I can quote the guide.....hang on,

**Comment by UselessGuru** [comment]
>  a discrepancy between the MultiPoolMiner expected income and the real balance

This is normal. You have given most answsers yourself. Possible reasons:
- miner reports higher than real rates (e.g. Lyry2z, see readme)
- pool lists higher than effectively paid prices
- stale shares, switching
- shares not being accounted by the pool because of pool hopping (depends on pools payout schema)
- pool 'stealing' shares
You will not get 'real' answer of where the discrepancy comes from. Each of the factors may can be involved to some extent.

> Can you link that math?
- MPM reads the published prices per GH/s and algo
- MPM reads the hash rate reported by the miner
- MPM multiplies these two numbers -> profit as displayed by MPM (mathematically very correct)

@fonyo: I think you should include something like this high up in the read me. This Q pops up so many times.

**Comment by papacheal** [comment]
Everyone's experience will vary based on desired target currency (keep the coins or auto-exchange), exchange rates, pool fees, reported hash rate vs. miner hash rate and obviously hardware.

My optimal setup (and this is just my personal experience) was:

- Selected the best performing algorithms for NVidia (for me) and did a clean benchmark of the best miners over a longer period of time (30 mins. minimum or "-interval 1800") to make sure their max hash rate was recorded in MPM as a baseline. I repeated this testing "intensity" settings on various miners that allowed them to maximize hash rate. 
- Adjusted the "allowed hash rate variance" in MPM from 10% down to 1% to avoid crippling my baseline rates with shorter runs of the miners in the future. See the README on how to do this, if you like.
- Selected two pools that I trusted and had reasonable fees/reputation. You don't want one that is so big that your shares are "drops in the ocean", but you also don't want one so small that you rarely mine the coins you're after.
- Ran MPM for a week to build up a "true" accuracy rating for the various pool/algorithm combos
- Used an "interval" of 5 minutes ("-interval 300"); most miners need that long to warm up to full hash rate from the pool's perspective and switching miners more often than that rarely helps. 

For what's it worth, I ended up (currently) with "ahashpool" and "miningpoolhub" for pools and the following algorithm/miner combos:

NeoScrypt - Palgin-Neoscrypt 1.0.1 - New specialty miner from PalginPav that is much better than other NeoScrypt'ers. The current release requires you to disable watchdog in MPM due to infrequent "combined hash rate" output to the console that would get it booted otherwise. Takes about 15-20 minutes to get up to max reported hash rate on multi-GPU rigs but it's worth the wait.
Lyra2z + Nist5 - TPruvot 2.2.4 (32-bit), custom intensity. Well built and stable miner. Much of the optimized kernels/code of previous standalone miners has been merged in this miner.
XEvan - CCMiner-XEvan (custom intensity). A specialty miner that just seems to do better for this specific algorithm
X17 - CCMiner-SP. Works well for X17, though this algorithm requires a decent CPU to pair with your GPUs to keep up: a Celeron/Pentium usually isn't enough. It's also a very busy algorithm these days, so profits have started to drop off.
Equihash - DSTM ZM v0.5.8. Great miner, only does Equihash but does it well.
LyraRE2 - ExcavatorNVidia1 - Using more that one worker isn't recommended on this miner; I'm hoping the dev team behind it releases some updates soon, now NiceHash is back.

All other pools, miners and protocols are disabled.

I feel that this is most stable/best earning setup for myself currently, but obviously will be tweaking it as I go: YMMV.

NiceHash is "nice" because it is dead simple, but they are a reseller of hashing service and introduce a middleman that leeches profits into the equation. You can always do better than them with a tuned MPM setup; you just need patience to do the leg-work to set it up.

**Comment by cmbconcretefire** [comment]
I'm just a fly in the ointment here. Lol. But I am trying to help others and that's what counts.

**Comment by cmbconcretefire** [comment]
@papacheal , would you please elaborate on your intensity adjustments? I have 6 x 1060's (6GB) and 6 x 1070's (8GB) and I have come to a similar conclusion as you regarding the best / fastest miners for me. Anyway, I know I could google intensity settings and such but it seems like we're running similar setups and I like your clear cut thoughts. Please share.

**Comment by komer83** [comment]
these are mine and not 100% completed, I simply edited ccminer files, all my cards are 1080ti's and OC is +80 +80, with neoscrypt the system is that responsive, but doesn't hangs up. 

Bitcore 20
Blake2s 26
Blakecoin 29
Nist5 22 
Phi 22
sia 30
Sib 21
Veltor 23 
X17 20
xevan 21 
neoscrypt 22
lyra2v2 23 
lyra2z  18 
skein   23

**Comment by Crypto00** [comment]
@komer83 I have 1080 Ti too so I'm trying your custom intensities in `CcminerKlaus.ps1`, `CcminerNanashi.ps1`, `CcminerSp.ps1` and `CcminerTpruvot.ps1` (other Ccminers*.ps1 don't have `"[Coin]" = "" #[Coin]` templates) with
```
    "bitcore" = " -i 20" #Bitcore
    "blake2s" = " -i 26" #Blake2s
    "blakecoin" = " -i 29" #Blakecoin
    "lyra2v2" = " -i 23" #Lyra2RE2
    "lyra2z" = " -i 18" #Lyra2z
    "neoscrypt" = " -i 22" #NeoScrypt
    "nist5" = " -i 22" #Nist5
    "phi" = " -i 22" #PHI
    "sia" = " -i 30" #Sia
    "sib" = " -i 21" #Sib
    "skein" = " -i 23" #Skein
    "veltor" = " -i 23" #Veltor
    "x17" = " -i 20" #X17
    "xevan" = " -i 21" #Xevan
```

MultiPoolMiner could also store a correlation table containing GPU models and refined intensities !

**Comment by papacheal** [comment]
My current rig is 4 x 1080Ti (Pwr 105%, CPU +100, Mem +250) + 1 x 1070. Intensities I've tweaked:

XEvan 21
Lyra2z 21
Nist5 24

I determined these intensities by increasing them until the miner crashed, then backing them down one by one to determine average hash rates at each level. I stopped when I found a delta on hash rate that I deemed significant enough to warrant the added intensity. Note these are NOT optimized for power usage; in some cases, I may be wasting intensity for the added hash rate but I haven't had the cycles to figure all that math out. Note that, overall, the intensity settings did not make an earthshattering difference to the hash rate so you can safely stick with defaults if you don't have the time. I just like squeezing a few extra H/s if I can.

**Comment by cmbconcretefire** [comment]
Thanks guys

**Comment by cmbconcretefire** [comment]
@papacheal , hey wait......you said > " I ended up (currently) with "ahashpool" and "miningpoolhub" < but the main page (somewhere) it says "Support for Ahashpool coming soon"....implying it's not supported yet. But you said you're using it. How? Cause I want to switch from Zpool.

**Comment by komer83** [comment]
@Crypto00 your OC is probably too high for my settings.

**Comment by sepa85** [comment]
Thanks for all the replies guys.. a lot of really useful information..

I just have a doubt about this:

> Adjusted the "allowed hash rate variance" in MPM from 10% down to 1% to avoid crippling my baseline rates with shorter runs of the miners in the future. See the README on how to do this, if you like.

Could you explain a little bit?

And about the Palgin-Neoscrypt 1.0.1, I have the same problem with the watchdog. Which could be the problem with disabling watchdog at all?

Thanks.. ;)

**Comment by UselessGuru** [comment]
> And about the Palgin-Neoscrypt 1.0.1, I have the same problem with the watchdog

This miner does not have a working API. MPM must use the wrapper instead. The wrapper attempts to read the hash rate from the miners screen output. Palgin sometimes takes much longer than $Interval to report the hash rate. -> Wrapper cannot get the hash rate -> watchdog kicks Palgin out of the list of available miners.

Solution: If you use Palgin you must disable the watchdog.

**Comment by fonyo** [comment]
@cmbconcretefire Ahashpool has been fully implemented for quite some time. We have blokmunch.club and ItalYiimp as well.

**Comment by papacheal** [comment]
@sepa85 I did some fine tuning as per the README notes (see Q18) to adjust the "fault tolerance limit" for hash rate detection for miners down to 1% from the default (10%). This "limit" is the maximum variance window from your current baseline hashrate where MPM will update your hashrate.

My problem was this:

1. I would do long baselines on miners (e.g. 30 mins. each) to get the true max hash rate of each.
2. I'd run MPM and let it do it's magic in switching miners, but frequently it would switch them before a miner got up to full hash rate. This is normal as most miners do need a decent amount of time to max out (15-30 minutes in some cases).
3. Leaving the default at "10% fault tolerance" meant that a miner that baselined at 100 MH/s would allow updates to its hash rate as soon as the miner crossed 90 MH/s.
4. If MPM decided to switch miners just after the example miner reached 90 MH/s, that miner would have been updated and MPM would now use 90 MH/s for it in future switching decisions. This effectively decreased the likelihood the miner would get picked in the future and didn't truly represent what that miner was capable of.
5. In worst case scenarios, the affected miner (now at 90 MH/s) could then be updated again in future runs to an even lower number if the miner crossed 81 MH/s (90 MH/s - 10%). And so on.

The solution was to re-do all my benchmarks again with 30 min. runs for each miner ("-interval 1800") after adjusting the "fault tolerance" to 0.01 from 0.1. This essentially locked in the max hash rate I'd determined for all my miners and only permitted very fine adjustments when the miner got within 1% of it's max. This, in turn, helped MPM make smarter decisions on profitable miners.

**Comment by sepa85** [comment]
Thanks @papacheal for the in-depth information..

**Comment by platinum4** [comment]
This seems to be have been opened once before at this issue as well: https://github.com/MultiPoolMiner/MultiPoolMiner/issues/695

**Comment by spoonjab** [comment]
It sounds like you are auto-exchanging to ETH. Try auto-exchanging to a different coin with lower fees like LTC. I ran into this same issue and switching to LTC made my expected earnings match much closer to actual payout.

**Comment by sepa85** [comment]
I thought that the transaction fees were included in the 0.2% from MPH.
If it's not, I definitively think that the main problem is this. If there is a fixed fee for every exchange, then my problem is the too frequent exchange.

**Comment by spoonjab** [comment]
The auto-exchange fee is 0.2%. However, I imagine that the gas fees required to make all the micro-transactions eat up quite a bit. I can't be positive; I know that LTC has way lower network fees and the total amount I receive is much closer to expectations when auto-exchanging to LTC. The testing  and losses I saw had nothing to do with the MPH fees or external wallet payout thresholds, so that is why I chalk it up to the ETH gas fees.

**Comment by rawbertp** [comment]
@papacheal How exactly did you change the fault tolerance to 0.01? I would do as follows but not sure if this is correct?
Change these lines:

```
   $ToleranceMin = $Stat.Week * (1 - [Math]::Min([Math]::Max($Stat.Week_Fluctuation * 2, 0.1), 0.9))
   $ToleranceMax = $Stat.Week * (1 + [Math]::Min([Math]::Max($Stat.Week_Fluctuation * 2, 0.1), 0.9))
```

to:

```
   $ToleranceMin = $Stat.Week * (1 - [Math]::Min([Math]::Max($Stat.Week_Fluctuation * 2, 0.01), 0.99))
   $ToleranceMax = $Stat.Week * (1 + [Math]::Min([Math]::Max($Stat.Week_Fluctuation * 2, 0.01), 0.99))
```

 0.**0**1), 0.9**9**))

**Comment by grantemsley** [comment]
Closing outdated issue for older version.
