### ISSUE TITLE
(Question) How to help improve MPM ?

### ISSUE THREAD

**Issue by komer83** [MultiPoolMiner/MultiPoolMiner#1046]
Other then the normal dev fees (what's that, 24 minutes a day or something?) Is there any other way to help if I'm just the average miner without programming experience? Like, can logs help the development team to track issues and stuff?

**Comment by fonyo** [comment]
Thank you for your question. The best way to help is keeping us posted with your experince (maybe even doing some testing), or what we could improve on, or looking out for new miners and pools we could add or any enhancement (new features even) you would want to see in the next releases. All inputs are appreciated and helps the project evolve. Cheers

**Comment by AdriaanVisser** [comment]
An added benefit in my opinion would be to add the other Claymore side-coins. Now only Siacoin is available, but Decred and Lbry are earning more (at least they used to in the NiceHash miner) as a side coin. Is this an issue you can fix, since I don't see decred or lbry listed at miningpoolhub either?

**Comment by UselessGuru** [comment]
> to add the other Claymore side-coins

All Claymore Dual mining coins are supported out of the box (decred, lbry, pascal, sia)
