### ISSUE TITLE
OpenCL error in VisualStudioCode & PowerGUI

### ISSUE THREAD

**Issue by UselessGuru** [MultiPoolMiner/MultiPoolMiner#1076]
In both dev environments I am greeted with the following error messages when starting MultiPoolMiner.ps1:
```

Add-Type : c:\Program Files\CryptoMining\MultiPoolMinerV2.6\OpenCL\Cl.cs(308) : Unexpected character '$'

c:\Program Files\CryptoMining\MultiPoolMinerV2.6\OpenCL\Cl.cs(307) :             if (count*elemSize < (int)arraySize) {

c:\Program Files\CryptoMining\MultiPoolMinerV2.6\OpenCL\Cl.cs(308) : >>>                 throw new InvalidOperationException($"Array size is incompatible with managed element size: array size = {arraySize}, sizeof({typeof(T)}) = {elemSize})");

c:\Program Files\CryptoMining\MultiPoolMinerV2.6\OpenCL\Cl.cs(309) :             }

At C:\Program Files\CryptoMining\MultiPoolMinerV2.6\Include.psm1:6 char:1
+ Add-Type -Path .\OpenCL\*.cs
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Power...peCompilerError:AddTypeCompilerError) [Add-Type], Exception
    + FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.AddTypeCommand
 
Add-Type : c:\Program Files\CryptoMining\MultiPoolMinerV2.6\OpenCL\CommandQueue.cs(151) : Unexpected character '$'

c:\Program Files\CryptoMining\MultiPoolMinerV2.6\OpenCL\CommandQueue.cs(150) :             if (buffer.Size < length) {

c:\Program Files\CryptoMining\MultiPoolMinerV2.6\OpenCL\CommandQueue.cs(151) : >>>                 throw new ArgumentException($"Memory buffer is to small: expected length >= {length}, found {buffer.Size}.");

c:\Program Files\CryptoMining\MultiPoolMinerV2.6\OpenCL\CommandQueue.cs(152) :             }

At C:\Program Files\CryptoMining\MultiPoolMinerV2.6\Include.psm1:6 char:1
+ Add-Type -Path .\OpenCL\*.cs
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Power...peCompilerError:AddTypeCompilerError) [Add-Type], Exception
    + FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.AddTypeCommand
 
Add-Type : Cannot add type. Compilation errors occurred.
At C:\Program Files\CryptoMining\MultiPoolMinerV2.6\Include.psm1:6 char:1
+ Add-Type -Path .\OpenCL\*.cs
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-Type], InvalidOperationException
    + FullyQualifiedErrorId : COMPILER_ERRORS,Microsoft.PowerShell.Commands.AddTypeCommand
```

When running MPM using start.bat everything is OK.

With older versions of MPMs OpenCL this does not happen, e.g. 
[OpenCL.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1647215/OpenCL.zip)

**Comment by grantemsley** [comment]
I've noticed this as well on systems that don't have powershell 6 (I'm still using 5.1 on a couple machines).

Perhaps visual studio and powergui are still using powershell 5 instead of 6?  Add a line to print $PSVersionTable right at the very top of the script and see what version it's using.

For now I just reverted to the old OpenCL version on those machines.  Old version works just fine.

The actual problem is that the new version is using [Interpolated Strings ](https://stackoverflow.com/questions/32878549/whats-with-the-dollar-sign-string), which is a feature of C# 6.  [Powershell 5 only uses C# 5](https://stackoverflow.com/questions/40787766/powershell-add-type-c-sharp-6-0).

Per that second link, there are ways to make it work with powershell 5, but they are kind of hacky and this is probably part of the reason support for anything but powershell 6 was dropped.

**Comment by UselessGuru** [comment]
> Perhaps visual studio and powergui are still using powershell 5 instead of 6? Add a line to print $PSVersionTable right at the very top of the script and see what version it's using.

Yep, still using 5.1

> For now I just reverted to the old OpenCL version on those machines. Old version works just fine.

Doing the same here.
