### ISSUE TITLE
Excavator 1.4.4a: Testusers wanted

### ISSUE THREAD

**Issue by UselessGuru** [MultiPoolMiner/MultiPoolMiner#1104]
Testusers wanted!

In an attempt to create AMD only and NVIDIA only miners I rewrote the Excavator miner files. This will fix https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1075
Since I do not own AMD hardware I need some assistance.

### **How to do do this quick test:**
**You need to have a mixed rig with AMD and NVIDIA cards installed**. Then

1. Manually update Excavator to the latest version
2. Delete all Stats\Excavator*.txt files (this will trigger benchmarking)
3. Move ALL miners files (except ExcavatorAmd1.ps1 from the zip file) to some other directory
4. Run MPM; It should begin mining **on all AMD cards** (check the miner screen), but it should **NOT use any NVIDIA card**. If this is true: Horray, step 1 done
5. Next: Stop MPM
6. Replace ExcavatorAmd1.ps1 with ExcavatorNvidia1.ps1 from the zip file
7. Start MPM; It should begin mining **on all NVIDIA cards** (check the miner screen), but it should **NOT use any AMD card**. If this is true: Horray, step 2 done. Mission completed!
8. Restore all other miner files (where did you put them in step 3???)
9. Report findings back here - thank you!

Manual Update of Excavator
Version 1.4.4 alpha NVIDIA: https://github.com/nicehash/excavator/releases/tag/v1.4.4a

You have to update manually, because Excavator is a proprietary software by NiceHash and has a special [EULA](https://github.com/nicehash/excavator/blob/master/excavator-EULA.txt).

Unfortunately I cannot verify this behavior from the content in the log files - so uploading logs won't help me :-(

**Comment by evanvz** [comment]
Hi @UselessGuru 

Not sure if you're still looking for this info or what info you require, but here we go.

[Data.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1660580/Data.zip)

**Comment by Braintelligence** [comment]
Ran a test on my 13x 1070 Ti rig now with these new .ps files and Excavator 1.4.1a Cuda 9.1 and 390.65 nvidia drivers:

## All algos:
- All 13 GPUs were recognized

## Blake2s
- 52,28GH/s with EN1, significantly higher than TPruvot (therefore best)
- EN2 seems to have failed
- Retry with EN2 and interval 300, now it seems to not crash. Benchmarked with 58,23GH/s

## Lbry
- Silently crashes after a few seconds, not sure why. MPM tried it 4 times until declaring as failed.
- 3,83GH/s with EN1, just a tad worse than TPruvot
- Retry Lbry with EN2 on interval 300, still silently crash after a few seconds, removed it from ps file

## Neoscrypt
- 10,59MH/s with EN1, significantly lower than Klaust or PalginNvidia (very bad)
- 11,34MH/s with EN2, closer but still significantly lower than Klaust or PalginNvidia which are both above 13MH/s for me
- I will try the EN2 one again with an interval of 300, since I heard it needs a bigger ramp-up time
- Retry EN2 with interval 300 aaaaaaaand it crashed. ***sigh***

## Nist5
- 658,13MH/s with ExcavatorNvidia2, significantly higher than TPruvot (therefore best for me)
- 595,95 MH/s with ExcavatorNvidia1 (worse, don't know what this means)

## Keccak
- 12,03 GH/s with ExcavatorNvidia2, significantly higher than Tpruvot
- 10,40 GH/s with EN1
- MPM declared Keccak as failed, didn't catch why
- Retried EN2 with interval 300, crashed as expected... MPM needed about 4 minutes to recover and start another algo

## Equihash
- MPM declared Equihash as failed at first, didn't catch why
- 6,45KH/s with EN2, significantly higher than DSTM (therefore best for me)
- 5,55KH/s with EN1, less than DSTM
- Retried EN2 with interval 300, but it crashed... damnit! Waited over 5 minutes for MPM to react and either start the next miner or restart Excavator but nothing happened. Restarted start.bat
- Another try again with interval 300 and very fast crash. Looks like I can't use EN2 for Equihash, which is a real bummer...

## Ethash
- Silently crashes after a few seconds. Same as Lbry.
- 348,49 MH/s with EN1, this is a lot worse than even Claymore Dual Mining ETH-performance
- Retry EN2 Ethash with interval 300, crashes instantly like before, removing Ethash entirely from Excavator

## Lyra2Re2
- 531,52MH/s with ExcavatorNvidia1, just a bit higher than CcminerLyra2re2 (therefore best for me)
- EN2 seems to crash, MPM tries several times to invoke it but it crashes after a few seconds. This keeps on until MPM declares it as failed. 
- Now on sixth time of EN2 it didn't crash as soon, produced a hashpower of 583MH/s in the console but then crashed after about a minute. (Looks to me like the json config is being adapted on every try?)
- 7th time also crashed
- 8th time same as sixth time but it worked it's way to almost 600MH/s, still crash
- 9th time we reach 602MH/s, still crash
![grafik](https://user-images.githubusercontent.com/6761196/35344949-a7b6bf14-012e-11e8-9f27-dc3fa9f80066.png)
- 10th time (how often will this go on?) it crashes again (I really wish I had logs at this point...)
- Didn't let it run for another time, restarted start.bat and it didn't even bother running lyra2re2 at this point

## Pascal
- 15,10GH/s with ExcavatorNvidia2, no other miner did work with Single Pascal until yet, so that's a good thing I guess
- EN1 kept running for several minutes in the benchmark, showed about 14,37GH/s - had to restart start.bat because it wouldn't kill the process by itself

**Comment by Braintelligence** [comment]
@UselessGuru Would love to hear your advice on how to find out why EN2 keeps crashing for so many algos.

**Comment by UselessGuru** [comment]
@evanvz

Thank you for the logs. But what I would like to know cannot be logged :-(

I have edited the test instructions to clarify the things to watch.

**Comment by evanvz** [comment]
Hi @UselessGuru 

Noted.

Seems @Braintelligence it a betetr job.

Just trying to give my 2c helping you with your great program.

Cheers.

**Comment by Braintelligence** [comment]
@evanvz I'm sorry, I don't understand what you wrote when you referred to me ☹️. What I wrote sadly won't help @UselessGuru at all, because I don't have AMD cards on that rig.

I hope that my observations can help others and maybe @UselessGuru might drop a hint on what I could try to optimize my rig and make EN2 work, since it looks promising for Equihash.

**Comment by fonyo** [comment]
@UselessGuru 
Can do some testing for you on Friday.

**Comment by UselessGuru** [comment]
> Are we talking VRAM (I mean: memory on GPU)

VRAM assume (I have 32GB of RAM in my box, 3 GPUs and are still getting the same errors)

**Comment by Braintelligence** [comment]
@UselessGuru I see, thanks for clarifying! So it could work on GTX 1080Ti with their 11GB VRAM?

**Comment by UselessGuru** [comment]
> So it could work on GTX 1080Ti with their 11GB VRAM?

Nope, some algogorithm use a percentage of available vram. If they take more than 50% then 2x 50% -> bang!

**Comment by Braintelligence** [comment]
@UselessGuru Makes sense, so this only works for some algorithms I guess. Crap. 😸

**Comment by UselessGuru** [comment]
@fonyo 

> Can do some testing for you on Friday.

[Make sure you use the updated version](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1663546/ExcavatorMiners.zip)

**Comment by geckah** [comment]
Tested 1.4.1a earlier with no crashes on my 3x1070ti,3x1080,1x1070 rig. 

However does this miner file use the pool file to determine the wallet address to use?
I added my nicehash internal wallet into the nicehash pool file but when excavator runs, it uses the -wallet info

**Comment by UselessGuru** [comment]
> added the direct path in the miner file for mpm to download and 1.4.2a is benchmarking now

You are supposed to do a manual DL and install. ;-)
Due to EULA restrictions we are not allowed to support automatic DL.

**Comment by geckah** [comment]
I tried the manual way. Must have fat fingers, couldnt get it to run. 

Am at a lost as to why only 2 out of 3 gpus are being used. Excavator picks up all 3 cards when initialising

**Comment by UselessGuru** [comment]
Please post the command line & json file

**Comment by UselessGuru** [comment]
@geckah 

Could you please post the output of the following command:  [OpenCl.Platform]::GetPlatformIDs() | ForEach-Object {[OpenCl.Device]::GetDeviceIDs($_, [OpenCl.DeviceType]::All)}
Also post an example of the created json files. Thank you.

**Comment by geckah** [comment]
Here is the json file
[NiceHash_Nist5_1_Nvidia.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1681619/NiceHash_Nist5_1_Nvidia.txt)

I'm sorry, but how do i get to output that command?

**Comment by UselessGuru** [comment]
> I'm sorry, but how do i get to output that command?

- Open a powershell session (pwsh.exe)
- type '[OpenCl.Platform]::GetPlatformIDs() | ForEach-Object {[OpenCl.Device]::GetDeviceIDs($_, [OpenCl.DeviceType]::All)} > somefile.name' and press enter
- upload somefile.name (where somefile.name) is a valid filename and path of your choice

**Comment by geckah** [comment]
getting an error with that command:

Unable to find type [OpenCl.Platform].
At line:1 char:1
+ [OpenCl.Platform]::GetPlatformIDs() | ForEach-Object {[OpenCl.Device] ...
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (OpenCl.Platform:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

**Comment by UselessGuru** [comment]
OK, run pwsh from the MPM directory
then type 'using module .\Include.psm1' and try again.

**Comment by geckah** [comment]
[somefile.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1681981/somefile.txt)
here you go

**Comment by geckah** [comment]
here you go 
[somefile.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1681987/somefile.txt)

**Comment by UselessGuru** [comment]
> somefile.txt

Thank you - I think I see the problem. Your CPU is also a GPU. I have updated the miner files:
[ExcavatorMiners.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1682635/ExcavatorMiners.zip)
Can you update and test - thank you!

**Comment by geckah** [comment]
> Thank you - I think I see the problem. Your CPU is also a GPU. I have updated the miner files:
ExcavatorMiners.zip
Can you update and test - thank you!

Sorry for the late reply. Testing now, all cards are being utilised now. Will update on the results then move on to test rigs with more gpus

**Comment by geckah** [comment]
nist5
alexis78cuda9 208MH/s
EN2 157.59MH/s
EN1 154.27MH/s

neoscrypt
EN1 3.55MH/s
klaust 3.18MH/s
EN2 fails to run, couldn't catch the error

lyra2v2
EN2 135MH/s
EN1 132MH/s
polytimos 131.95MH/s

blake2s
polytimos 13.02gh/s
EN1 12.52gh/s
EN2 12.4gh/s

**Comment by UselessGuru** [comment]
> Testing now, all cards are being utilised now

Thank you. Good to hear!

> EN2 fails to run, couldn't catch the error

That is somehow to be expected, some GPUs eat up too much VRAM. Let MPM fail during benchmark, it will report 0 hash rate and will never try this miner/algo combination anymore.

**Comment by UselessGuru** [comment]
Obsolete with https://github.com/MultiPoolMiner/MultiPoolMiner/commit/a0857c0757ac2577df7c2631e31d746383d5a442
