### ISSUE TITLE
Add 2Miners.com mining pools 

### ISSUE THREAD

**Issue by sneg55** [MultiPoolMiner/MultiPoolMiner#1119]
Hi, 
I'm wondering if you can add our pools https://2miners.com to your app? 
We have well-documented API here: https://apidoc.2miners.com

**Comment by aaronsace** [comment]
Interesting, can you provide a direct link to the 'price per hash' and the 'total pool hash rate'?

**Comment by sneg55** [comment]
For example for eth pool: https://eth.2miners.com/api/stats 
"hashrate": 160003380821 
it's total eth pool hashrate. 
But we do not have  'price per hash'

**Comment by aaronsace** [comment]
How do you propose the real-time profit information is obtained?

**Comment by sneg55** [comment]
I thought that you are calculating it on your side? Otherwise, pools can return any fake price per hash rates from API.

**Comment by 3zero2** [comment]
@sneg55 raises a good point. Relying solely on data from API might not be the best way looking forward. The more MPM becomes popular the bigger incentive a pool would have from altering (even if slightly) the price per hash reported in the APIs.

I would trust more any method MPM implements (even if not accurate 100%) to calculate the price per hash rather than what is reported by the pools' APIs.

**Comment by aaronsace** [comment]
@3zero2 Not even sure that's possible to implement.
