### ISSUE TITLE
Globally Change Work Intensity

### ISSUE THREAD

**Issue by korishan** [MultiPoolMiner/MultiPoolMiner#1143]
Could we have a way to globally change the work intensity for CPU/GPU (separately). With my current rig, the default intensity of about 15 on some of the miners makes my system skip a lot, especially videos. Dropping the intensity down 2 points smooths things out nicely.

Maybe even make it so that we can change it on the fly from the main MPM screen.

Thanks,
Kori

**Comment by ChriscomIT** [comment]
+1 for this improvement as it would be also great for unstable machines and OC testing.

**Comment by UselessGuru** [comment]
This is an almost impossible task.
MPM was designed written in powershell so advanced users can modify and fine tune their installation.

The creators of MPM can not maintain a consolidated parameter list for each available configuration. The base configuration should be good for most. 

There are so many different card types, models and manufacturers. Each one would require individual default parameters per algo and miner binary.

What **may** come in the future is a separate configuration section in config.txt for parameters like intensity or cuda block size per algorithm and miner binary so you won't lose personal customization on updates.

**Comment by korishan** [comment]
There's already a place to store the config information for each miner in the "Miners" folder. From looking at several .ps1 files, there's an Argument section. I was figuring that the intensity could be added here (for those miners that take that as an argument) and it could be based on a global percentage set from MPM.
So, while MPM is running, pressing key combinations, say:
Press G to access GPU settings. Then press I to access the Intensity setting, then press the +/- keys to change the Percentage value, or type the numerical value in.
Then, closing the miner would tell MPM to relaunch the miner and adjust the intensity accordingly. Or, just changing the intensity would automatically restart the appropriate miner with the new settings.

Just a thought. I'm not a programmer in this area, so I don't know if that can be done or not. It sounds good in my head, at least  :P

**Comment by grantemsley** [comment]
@korishan The problem is, each and every miner has a different way of adjusting the intensity.  And some cards only work at certain intensities, and above that they crash, while others cards are fine.  And what lags one person's system doesn't lag another's.

What may be possible at some point is to have the ability in the configuration to pass additional arbitrary arguments to each miner, and let you control the intensity in the configuration - but you get to do the fun part of figuring out what the optimal settings are for each miner, for each algorithm it mines.
