### ISSUE TITLE
Fine tuning of -dcri for ClaymoreDual

### ISSUE THREAD

**Issue by nitrobg** [MultiPoolMiner/MultiPoolMiner#117]
-dcri 20, 30 and 40 are not precise enough to determine the best speeds for dual mining. The app needs to be able to tweak it up and down depending on the combination.
On my 480, dcri 18 gives me 28/500MH/s which is slightly more profitable than the suggested Dual30 (22/660MH/s).

**Comment by aaronsace** [comment]
All the miners are not fined tuned but set with reasonable settings; you can edit each miner yourself. 

I could implement code to fine tune everything but it would take a considerable amount of time. 
I'll think about it.

**Comment by fonyo** [comment]
Well, it would also take a considerable time to benchmark each dcri. Not even mentioning, some of them for some reason are not liked by some cards (they freeze). Does claymore's api work with controlling the dcri value? If so, I definitely suggest using that instead of reloading the miner. BTW, @nitrobg look at my extreme benchmarking thread here in the issues section. I know what you are saying but adding too many dcri presets are not feasible for an average user for many reasons. Although, you can do the same as I did and create your own preferred values. All of them even if you are patient and really need them and I have to say it's definitely worth your trouble. Extreme benchmarking should be added as a feature @aaronsace. I know it's not difficult to do, rather tedious but I can provide you with all the files if you implement the feature and save you some time creating the files. Please consider it, because it does create a lot more profit when SC has a higher value like these days.

**Comment by fonyo** [comment]
It wouldn't even be hard to implement. Just add a switch that either ignores the extra files or not. Almost 7 usd per card (RX 480)! That would be way less with dual20 or 30. It hovers around 25 ATM. Please do consider adding this feature. Users are always happy to earn more. Currently, as far as I'm aware, your script is the only one that can determine the best dcri value for the most profit when all the dcri values are benchmarked. They are also organised with the most profitable dcri being on top. So there is also visual feedback why MPM would switch. I love it. Pretty please.

**Comment by aaronsace** [comment]
I'm looking into integrating the APIs further and will look at trying to get something that works quick and reliably.

**Comment by imrecsoka** [comment]
Once i have another graphics card i will donate 45 minutes to you -donate 45. I hope this is reasonable.

Oh i find skein and groetsl and myriad they are terrible for me because they use sgminer...
i dont know, but whatever uses sgminer for me is always terrible.
Unless somebody can show me how to use it properly, but then again its being run by multipoolminer so i should not have  to right ?

**Comment by aaronsace** [comment]
I don't like most of the miners but it's what we have to work with. I am going to do some sgminer benchmarking and review the settings.

**Comment by alucard20724** [comment]
the current values of 20,30,40 are fine for AMD cards.  my GTX10x0 cards are near 80,90,100.. and then i do a little tweaking +/- 1 til i get closure to the best one... and i leave all the bench marks there.  It will pick the most profitable one and mine that.... i.e. +19 might be more profitable today, but tomorrow +20 might be more profitable.  Benchmark as much as you feel comfortable with and let mpm do the rest.

**Comment by imrecsoka** [comment]
Hi alucard i do not know what you mean by 20,30,40 .... what , intensity ?
I am a beginner been mining for several weeks now but i need layman's terms and im sure more here need that.
When you say current values of ..... do u men leave the application as is? because this is what i did/do.
Sgminer is just a ridiculous miner if u ask me.
It either doesn't pump/push  my AMD card. If i try to "g"  then "i"  then select GPU number then value for intensity , my machine hangs or the the screen goes blank and the drivers crashes and the temperatures are sitting at 50 to 60 degrees Celsius, so it makes no sense.

**Comment by alucard20724** [comment]
those are the intensities... aaron has setup for everyone ClaymoreDual20, ClaymoreDual30, and ClaymoreDual40 in the miners folder.  if you open each miner, you'll see -dcri 20, -dcri 30, and -dcri 40 respectively... they work great for a starting point for AMD cards... nvidia cards work better with 80, 90, 100 as a start.   If you look at/in each text document, you'll see the miner it calls.... 
as for running.. **just change the name for user and worker in the start.bat file.  and the -type and -algo if you want**.

I just use multipoolminer... it's simple and straight forward script that calls the programs it needs.  works out really well.

**Comment by UselessGuru** [comment]
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1237 should help :-)
