### ISSUE TITLE
I don't understand why you're ignoring the facts

### ISSUE THREAD

**Issue by ztowne13** [MultiPoolMiner/MultiPoolMiner#1184]
(cont. of #1177 because he locked it and won't address the issues)

LOOK, I don't care if you fix it, I just want you to honestly address the issue.

Can you please explain to me how it's a bug... I didn't have time to write this post at the exact time of my discoveries but yesterday I booted NiceHash with only Equihash and MiningpoolHub + NiceHash with only equihash and NiceHash's equihash algorithm WAS 100% more profitable without a doubt (and the accuracy is not low at all). This is 100% a bug in the code, please stop denying it because NiceHash Equihash pool being mined at over .0008 BTC/day compared to MPH's ZCash equihash pool being at around .0007 BTC/day is DEFINITELY more profitable. And I understand my pictures don't show that fact but you and I both know that profitability of certain algos on certain pools goes up and down with time...

Regardless, even if it wasn't more profitable EVER, why does MPM have to show all of the useless algos like LBRY or Groestl or Keccak (yes I know I have them enabled - but I also have equihash enabled) that are ALSO not profitable ever and not show the equihash algorithm so I can at least see it's profitability.

I'm not trying to attack you, your program is fantastic and I really appreciate the work you've done, I just feel like you're getting very defensive over something that I don't see how it could otherwise be a bug...

**Comment by UselessGuru** [comment]
> Can you please explain to me how it's a bug...

I seriously doubt there is a bug in that area. If there were lots of people yould complain. It somehow tricky to understand the way MPM calculates the best paying miner/algo. [Readme explains it quite well](https://github.com/MultiPoolMiner/MultiPoolMiner#multipoolminers-logic), and a lot of effort has gone into make the explanation 'dummy proof'.

If MPM makes miscalculations then it might be caused by broken stats information. Reset your stats and let MPM run - it will (after a few loops!) determine the best paying miner/algorithms combo. Note that MPM does not always jump at the best paying pool/miner/algo each time someting seems to pay better, MPM uses data gather over time to find the pest profit in the long run.

> why does MPM have to show all of the useless algos like LBRY or Groestl or Keccak

Because you have enabled them. Only enable the algos you are interested in.

**Comment by ztowne13** [comment]
I thought I made it clear that I completely understand how the profitability calculations work. Please don't call me a dummy because I'm informed on how the program works. It's not making miscalculations for the profitability - It's not looking at the NiceHash Equihash pool AT ALL. Maybe try reading the post I tagged - it'll give context to the situation.

Did I not make it clear that I understand I have the useless algorithms enabled. I was just pointing out that apparently I also have the useless equihash algorithm enabled but it STILL doesn't show it.

**Comment by aaronsace** [comment]
@ztowne13 If you post this again then you will be banned.
