### ISSUE TITLE
Excavator on NiceHash when running as Job

### ISSUE THREAD

**Issue by sageau-adam** [MultiPoolMiner/MultiPoolMiner#1185]
Trying out the latest master (f9d0f5b1fe57075eed71d623d3116db8ff0e706d at time of writing) - I have MPM using NiceHash pool, running excavator.
NiceHash does not report or seem to generate BTC for any work done by Excavator.
I had 2 hours logged of Lyra2REv2 and 30 minutes of Nist5 - both balances showed as 0.
While running algorithms on Excavator - NiceHash showed them as active workers but never reported a hashrate apart from 0 MH/s
Running Equihash on DSTM reported correct.

I reverted the code to make the miners run as processes again instead of jobs - Excavator now reports correctly to NiceHash.
Seems to be an issue with excavator and not reporting speeds when it doesn't have a window.

**Comment by grantemsley** [comment]
I haven't tried the latest master...does it make the miners not have a window?

I know there are a few miners that really don't react well to not having a console window.

**Comment by sageau-adam** [comment]
Yeah - the latest master has the miners run as Jobs - these don't have console windows in the current implementation.

Just thought I'd bring it up as a potential problem of the implementation

**Comment by aaronsace** [comment]
I doubt it has anything todo with hiding the miner windows. The miner windows are now text files inside the logs folder that can now be fed anywhere in realtime, even back into a console window. Also, you can no longer have stray processes and are now actually sub-processes (check task manager). 

Hopefully NiceHash are not being stupid with this; I'm trying to rewrite the excavator implantation so this is the point that I need to know.

**Comment by titvs** [comment]
@aaronsace Are you going to implement somekind of live monitoring of the miner that is running? There are some miners that return errors or need to be killed for whatever reason, so a live view of whats the miner doing would be great.
This is a good ideia since you get a log for each miner, but not having a monitor window on this last implementation is a bit a down side...

**Comment by sageau-adam** [comment]
@aaronsace I'm not totally sure what NiceHash have done, but from what I've read they did not want Excavator to ever be 'hidden'. I saw one issue reported on their Git about not showing hashrates on NiceHash to which the dev asked - is the console widow being hidden? - and then marked as resolved.

Could well be they have it set to not report 0 hashrate if they have no console window somehow.

But I haven't done extensive enough testing to know for sure - all I have to go in is this:
Running excavator.exe with changes from c768136c5caf893cba9b8a1c02b7f2040186a763 reports hash rates to MPM, but to NiceHash's dashboard it is 0
Without changing anything else and reverting code changes back to processes, both MPM and NH dashboard are showing hashrates.

**Comment by grantemsley** [comment]
@sageau-adam is likely referring to this ticket: https://github.com/nicehash/excavator/issues/45

There was a point where nicehash stopped hiding some of the console windows.  I can't remember whether it was intentional to make using it in a botnet less attractive, or due to some defect in the miner, but the console windows couldn't be hidden, only minimized.
