### ISSUE TITLE
Pre-Release 2.7.2: Excavator not starting

### ISSUE THREAD

**Issue by boro2000** [MultiPoolMiner/MultiPoolMiner#1212]
Unfortunatly the Excavator is not being started in the new pre-release 2.**7**.2.
MPM tries, but nothing happens, then it is sorted to "Status: Failed"

**Comment by UselessGuru** [comment]
@boro2000 

What version are you referring to? 2.4.2 does not exist.

Which Excavator files are you using? May I ask you to try these:
https://github.com/MultiPoolMiner/MultiPoolMiner/files/1682635/ExcavatorMiners.zip

**Comment by borzaka** [comment]
Do you mean v2.7.2? :)

- Excavator can be closed due to too much overclock. Try with stock settings.
- You should see an error before Excavator closes. Try to printscreen it.
- Are you sure you put Excavator to the [right place](https://github.com/MultiPoolMiner/MultiPoolMiner#q9-multipoolminer-says-it-cannot-find-excavatorexe)?
- Are you using the [latest Excavator](https://github.com/nicehash/excavator/releases)?
- Some MPM Excavator settings won't work with every computer. For example NeoScrypt with 2 thread (ExcavatorNvidia2) don't work for me, only 1 thread (ExcavatorNvidia1) works. This is normal. You should get at least one benchmark result from every Excavator supported algos.

**Comment by boro2000** [comment]
Yes, of course I refer to v2.7.2 :) Sorry.
- It is the actual version of Excavator, and it's in the right place
- There is no error message, the log file(s) do not show anything.
- Excavator runs perfect for the same hardware-setup and settings, using MPM in a master-version just one step before the commit https://github.com/MultiPoolMiner/MultiPoolMiner/commit/c768136c5caf893cba9b8a1c02b7f2040186a763

**Comment by aaronsace** [comment]
@boro2000 FYI You should see the actual Excavator window appear in the taskbar as it doesn't use that commit in 2.7.2.

**Comment by boro2000** [comment]
@aaronsace Thanks for the info, yes, I have seen your work in APIs/NiceHash.ps1 (btw THANK you very much for the many efforts, you put into this project!). Excavator did not shine up in the taskbar.

**Comment by aaronsace** [comment]
I'm going to try a quick patch then I'll post the commit.

**Comment by boro2000** [comment]
Super!! Thanks in forward!

**Comment by aaronsace** [comment]
Can't really test ATM but I think that's the mistake that I made on the last commit before release: 82076bd5f7b3a8a66e490626e8dfd724c77a8e1b

**Comment by boro2000** [comment]
Beautiful, Excavator is starting, now.
