### ISSUE TITLE
Unhide miner windows

### ISSUE THREAD

**Issue by SaintPistachio** [MultiPoolMiner/MultiPoolMiner#1215]
Would it be possible to allow miner windows to not be hidden? Maybe a switch in the cmd line?

**Comment by aaronsace** [comment]
Not at the moment; the miner windows are inside the logs folder instead of the screen.

**Comment by khaotekmetalcraft** [comment]
+1 unhide.

running hacked without donate until then.  some of us like to supervise little shits like you as to be aware of your back end bullshit and monitor the shenannigans.   stop wasting our time with trivial shit form.  always....function, before form.  fix your broke.  no monies, kthnx.

**Comment by aaronsace** [comment]
@khaotekmetalcraft This miner and my life is 100% public and you are now banned.

**Comment by adam-g-100** [comment]
Yes please +1 for me too. This is really frustrating not being able to see the mining console.

**Comment by Renegade5399** [comment]
I haven't grabbed the latest master version yet. Does it just dump the miner window output to a text file? If so, you can just use notepad++ with the Document Monitor plugin activated to view it real time. I use it all the time when troubleshooting server issues here at work since they are windows based.

**Comment by aaronsace** [comment]
@Renegade5399 Yes the text files are coming straight from the miner consoles instead of being rendered on the screen. It's far easier remotely looking at text files than using teamviewer and you have ALL the history in date order. Also, the main MultiPoolMiner log stores a second copy of the miner outputs every 60 seconds. 

The processes are now managed by Microsofts well text 'jobs' instead of custom code that was buggy.

**Comment by aaronsace** [comment]
This is a handy command in PowerShell if it helps anyone: `Get-Content .\Logs\Log.txt -Wait`

**Comment by orangeclaimer** [comment]
`at the moment but the miner windows are inside the logs folder instead of the screen`

We know now that we can find the data there. Anyways, could you still make it possible to make it look like it it before? So we can choose atleast. It would be really nice if you could do that.

thank you

**Comment by orangeclaimer** [comment]
@aaronsace Since MPM doesn't open all the little miner windows now, is the switch from one algo to the next faster? Does is start mining earlier than it would if you would open the miner windows?

**Comment by aaronsace** [comment]
It's smoother but not faster. Switching improvements are coming in 2.7.3.

**Comment by aaronsace** [comment]
e30849448f88556725eb5ae6d6c02b8cfa3d0d37
