### ISSUE TITLE
issues with new release V2.7.2

### ISSUE THREAD

**Issue by amolitor** [MultiPoolMiner/MultiPoolMiner#1224]
Heya there, first of all, awesome work, just love how this tool helps me mine better.
I downloaded this new version , copied the old benchs and let it sit for 2h. But found these issues so far:
1 - in the monitoring screen, it's not showing somehow the current speed of the worker  as you can see with the link bellow:
https://ibb.co/cnphBS
2 - Bellow are all my log files, it , shows the new benchmarks it done with the new miners + the connection issues i was having trying to mine with dstm..
[Dstm-2222_2018-02-13_17-43-45.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1721440/Dstm-2222_2018-02-13_17-43-45.txt)
[MultiPoolMiner_2018-02-13.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1721441/MultiPoolMiner_2018-02-13.txt)
[MultiPoolMiner_2018-02-13_17-00-43.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1721442/MultiPoolMiner_2018-02-13_17-00-43.txt)

[PhoenixMinerNvidia-23334_2018-02-13_17-28-40.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1721443/PhoenixMinerNvidia-23334_2018-02-13_17-28-40.txt)
[Prospector-42000_2018-02-13_17-33-13.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1721444/Prospector-42000_2018-02-13_17-33-13.txt)
[BMiner-1880_2018-02-13_17-13-31.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1721445/BMiner-1880_2018-02-13_17-13-31.txt)
[BMiner-1880_2018-02-13_17-34-58.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1721446/BMiner-1880_2018-02-13_17-34-58.txt)
[BMiner-1880_2018-02-13_17-37-47.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1721447/BMiner-1880_2018-02-13_17-37-47.txt)
[BMiner-1880_2018-02-13_17-40-24.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1721448/BMiner-1880_2018-02-13_17-40-24.txt)
[Dstm-2222_2018-02-13_17-36-27.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1721449/Dstm-2222_2018-02-13_17-36-27.txt)
[Dstm-2222_2018-02-13_17-39-05.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1721450/Dstm-2222_2018-02-13_17-39-05.txt)
[Dstm-2222_2018-02-13_17-41-26.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1721451/Dstm-2222_2018-02-13_17-41-26.txt)
[Dstm-2222_2018-02-13_17-42-44.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1721452/Dstm-2222_2018-02-13_17-42-44.txt)

hope it helps somewhere..

**Comment by titvs** [comment]
@amolitor, ive noticed that you are running a rig with nvidia cards from the 9xx and 10xx series. Without wanting to hijack your issue, can i contact you, since im trying to build a mining rig myself but im running into stability problems when using a card mix similar to yours... Any advice would help. Thanks

**Comment by amolitor** [comment]
sure, send me w/e doubts you got.

**Comment by titvs** [comment]
I was able to put up a mining rig with these specs:

- Msi motherboard Z270-A Pro (the only one i found in stock)
- Pentium G4560
- 4 Gb RAM Hyperx
- Dual PSU, 400 + 1000W
- Windows 10 x64 latest
- 2x 1050 Ti (to be replaced for 1060s)
- 1x 1070
- 1x 980

After a lot of experimenting i tought i had a stable rig but it crashes the DSTM miner without anykind of overclock. If i replace the 980 card for a 1070 Ti, it works flawlessly.
Do you have all your cards on risers? use IGP? Any special BIOS settings (above 4g, gen 1,2, etc.)?
I find peculiar that it seems to exist somekind of incompatibility between these 2 generations and the motherboard... Any insight would help, since im a first time miner with dedicated hardware. :)

Thanks!

**Comment by amolitor** [comment]
all 1080 ti's are on risers .. 980 is on normal pcie. gen auto and above 4g on
If is  crashing the miner, post log somewhere, and what coin were you mining and which pool were you using ?

**Comment by m-bosch** [comment]
@amolitor  @titvs this goes off-topic I think. try to contact of GitHub.

**Comment by titvs** [comment]
Same settings/pool in both situations... I agree its a bit off-topic @m-bosch... will try other configurations and a setup similar to @amolitor. You can close the issue.

**Comment by amolitor** [comment]
@m-bosch  sorry. @titvs send contact thru git if you wanna continue to chat..
