### ISSUE TITLE
Excavator does not run with 2.7.2

### ISSUE THREAD

**Issue by Kettoch** [MultiPoolMiner/MultiPoolMiner#1227]
So I have seen another that was completed and closed but mine seems to still have an issue.

I am not sure what path it starts these in but if the path in the log is an indication, I copy the same command line into a prompt and it does not find the file.

I fix it so that it does work and the MPM will not launch it successfully but the same command line run manually works.

It does not seem to launch long enough to see it in task manager.

The calling convention seems to be an issue.  I have done a fair amount of powershell but I cannot determine quite why other than it does not like being hidden.  Do not know if that is the case yet.

[MultiPoolMiner_2018-02-13.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1722194/MultiPoolMiner_2018-02-13.txt)

**Comment by UselessGuru** [comment]
>  it does not find the file.

The JSON files are stored in the miners bin file, in your case 'C:\MultiPoolMiner\Bin\Excavator\'

Are you running the 'stock' Excavator files, or [these](https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1104)? (please try them - I need feedback)

Can you find ANY recent JSON files?

**Comment by aaronsace** [comment]
Are you definitely running this patch: 82076bd5f7b3a8a66e490626e8dfd724c77a8e1b

**Comment by cmbconcretefire** [comment]
OP, the instructions say you "WILL" need excavator, and tells you where to download it from. Truth be told, I've never been able to get Excavator to so much as benchmark in MPM. I looked at the config files once because I wondered why there was an "nvidia1 and nvidia2" file. The only difference I could see right away was the 1 used 1 thread and the 2 used 2 threads. 

Either way, doesn't matter to me because I have never been able to even benchmark Excavator in MPM and, I've straight up been told by a high level team member involved with MPM to delete the Excavator files because excavator miner is a sub-par miner anyway. I took his advice, deleted the Excavator config files, along with everything "AMD" and "CPU" related (as I don't use AMD cards nor my CPU) and now I can benchmark things just fine.

**Comment by Kettoch** [comment]
I do believe I was before I added a path change to see if that was the issue but going back to stock causes the same problem.

**Comment by Kettoch** [comment]
@aaronsace : I do not think I am.  I will try that next.

**Comment by aaronsace** [comment]
Improvements are been moved forward to v2.7.3 instead but Excavator should be working for now with that patch. 

Reopen the issue if it's still not working.
