### ISSUE TITLE
WARNING: Stat file (Dstm_Equihash_HashRate)  in pre-release 2.7.2

### ISSUE THREAD

**Issue by m-bosch** [MultiPoolMiner/MultiPoolMiner#1235]
```
WARNING: Stat file (Dstm_Equihash_HashRate) was not updated because the value (1328) is outside fault tolerance (1415 to 1729).
WARNING: Pool prices are out of sync.
```

Logging:
[MultiPoolMiner_2018-02-14_17-35-29.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1724935/MultiPoolMiner_2018-02-14_17-35-29.txt)

**Comment by grantemsley** [comment]
This is normal.  It means the miner is running slower than the benchmarked speed +/- a certain percentage.  Usually that's because something else is using the computer, or because the miner hasn't gotten up to speed yet.

All it means is that it's not adding that particular measurement to your benchmarking stats, so it won't affect the average speed.

If you are always getting this message, you should rebenchmark your machine.

**Comment by m-bosch** [comment]
Ok thanks. my rig restarted 'unknown' 20 minutes before so the mpm wasn't running for a long time unfortunately.

case closed
