### ISSUE TITLE
While running 2.7.2.1 getting notified there is an updated version available

### ISSUE THREAD

**Issue by hapklaar** [MultiPoolMiner/MultiPoolMiner#1255]
WARNING: Pool prices are out of sync.
WARNING: The software (MultiPoolMiner) is out of date; there is an updated version available at https://github.com/MultiPoolMiner/MultiPoolMiner/releases/download/v2.7.1.4/MultiPoolMinerV2.7.1.4.zip.

**Comment by nickvasel** [comment]
I was just going to add this...Logs added as needed.
WARNING: Pool prices are out of sync.

[MultiPoolMiner_2018-02-17.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1733739/MultiPoolMiner_2018-02-17.txt)
[Start-MiningPoolHub.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1733740/Start-MiningPoolHub.txt)

**Comment by nickvasel** [comment]
USD/GH/Day seem a bit off?

**Comment by titvs** [comment]
Im also getting the "WARNING: Pool prices are out of sync." on the latest commit...

**Comment by Gandalf15net** [comment]
Same here: WARNING: Pool prices are out of sync

I got told to remove zpool, that is no option though

**Comment by paulskulis** [comment]
Just wanted to confirm, I am also having this issue. MPM eventually downgraded itself.

**Comment by titvs** [comment]
Benchmarking this latest commit gave me the errors above, but ive also noticed that are some miners that arent getting logged. I cant seem to find the logs for Equihash-EWBF and Cryptonight-FireIce. Also, Excavator doesnt get logged but i guess thats because its window pops up.
Did anybody else noticed miners not being logged?

Ive also an enhancement to propose: at the beginning of each miner log, can you guys please include the launch command line? It would help in troubleshooting a particular miner that returns errors.

With the miners hidden gets a bit more difficult to troubleshoot problematic miners. Prospector is one of them (which development seems to be abandoned). This miner has a problem on some boards and gets stuck on a loop: [https://github.com/semtexzv/Prospector/issues/21](url). Now the process has to be killed on the Task Manager.

The monitor window would be a great addition!

Keep up the great work.
