### ISSUE TITLE
help...mpm starts and stops a lot?

### ISSUE THREAD

**Issue by d0n4ald** [MultiPoolMiner/MultiPoolMiner#1348]
i finished benchmarking equihash and lyra2re.  now mpm seems to start and stop hashing multiple time. see from the picture. its "start waiting before next run" whatever that means. in the older mpm versions, theres no pause or interruptions in hashing, its constant hashing
![image](https://user-images.githubusercontent.com/34756410/36826980-b0066586-1cde-11e8-9acc-2c907d2ee792.png)

**Comment by jeetbarman** [comment]
My running minner again restart miner which in return is always keeping accepted share value in lower segment.

**Comment by UselessGuru** [comment]
> My running minner again restart miner which in return is always keeping accepted share value in lower segment.

??? I do not want to be rude, but I do not understand.

**Comment by jeetbarman** [comment]
@UselessGuru I am connected via mobile for which I am unable to upload log but same will be done shortly.

Issue: Bminer starts mining and after 60 second it validate profitable coin and again initiate bminer startup command.

This was not happening with earlier build and if Equihash algorithm was profitable with bminer then same would continue and increase accepted share value but now it's different and since bminer is getting restarted Everytime accepted  share value always remain 3 or 4.

**Comment by UselessGuru** [comment]
If you feel MPM is switching too often then make sure you have this: 
https://github.com/MultiPoolMiner/MultiPoolMiner/commit/aac63a91c5fb22c147cdef64d4a63970a9fef453

**Comment by boro2000** [comment]
@jeetbarman 
there is a bug in mpm that kills bminer every 60 seconds (https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1306).
I already proposed a patch for that: https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1329/commits/f019e69875e434c42f1cfe7e747c8e41858eba90
Try to apply it :)

**Comment by jeetbarman** [comment]
@boro2000 I think you understood what I am trying to say, will definitely give it a try and let you know if it solves.

**Comment by jeetbarman** [comment]
While using older version I can see Bminer.exe is started and after 60 second if it's still profitable then it save hash rates and start reflecting current speed with no. of accepted share.
![image](https://user-images.githubusercontent.com/36787233/36848789-47962a7c-1d88-11e8-9b49-2becbc386739.png)

While using latest version Bminer startup command gets initiated again and again, although it's marked as most profitable.
![image](https://user-images.githubusercontent.com/36787233/36851544-7585b39c-1d8f-11e8-8d68-359c4c33fa3d.png)
![image](https://user-images.githubusercontent.com/36787233/36851606-96b5c53e-1d8f-11e8-9ea7-a3541cc4104b.png)

**Comment by jeetbarman** [comment]
Log from older Version:
[MultiPoolMiner_2018-03-01_15-22-59.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1771622/MultiPoolMiner_2018-03-01_15-22-59.txt)


Log from latest Version: 
[MultiPoolMiner_2018-03-01.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1771615/MultiPoolMiner_2018-03-01.txt)

**Comment by boro2000** [comment]
That does in deed look like the mpm-kills-bminer bug. Try the patch https://github.com/MultiPoolMiner/MultiPoolMiner/commit/f019e69875e434c42f1cfe7e747c8e41858eba90 .
Your problem will be solved, most probably.

**Comment by UselessGuru** [comment]
@d0n4ald 

Try https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1353

**Comment by boro2000** [comment]
@UselessGuru 
Supernice! I did not know about the watchdog parameter for bminer.

**Comment by jeetbarman** [comment]
@UselessGuru Thank You 
@boro2000 
Since I am new to this editing hence validating my action before committing it.

I am deleting below line from BMiner.txt

"Arguments":  "\"-api 127.0.0.1:1880 -uri $(if ($Pools.Equihash.SSL) {'stratum+ssl'}else {'stratum'})://$($Pools.Equihash.User):$($Pools.Equihash.Pass)@$($Pools.Equihash.Host):$($Pools.Equihash.Port) -nofee\"",

& replacing it with  below line.

"Arguments":  "\"-api 127.0.0.1:1880 -uri $(if ($Pools.Equihash.SSL) {'stratum+ssl'}else {'stratum'})://$($Pools.Equihash.User):$($Pools.Equihash.Pass)@$($Pools.Equihash.Host):$($Pools.Equihash.Port) -nofee -watchdog=false\"",

**Comment by UselessGuru** [comment]
Yes. Or in other words: just insert  "--watchdog=false"

**Comment by UselessGuru** [comment]
Fixed with https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1353
