### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by spartan5v5** [MultiPoolMiner/MultiPoolMiner#1378]
![captura de pantalla 2018-03-04 a las 8 48 56](https://user-images.githubusercontent.com/37022773/36944135-3d95b28a-1f96-11e8-8cf9-e8707f7b6888.png)

I dont get 0,00234

**Comment by mkirov0** [comment]
I hope this is a real question so I will try to answer.
This is a feature of MPM that shows you the benefits of using the  mult- algo, multi-pool software.
In your case it looks like it has been affected by the recent change by zPool in their estimated price of the keccak algo. Could be something else, but the fluctuation just seems too big, so I am assuming its an error or a bug like the mentioned above.
You can reset profits and will fix it (I wouldn't since the data is essential to how MPM works).
Or you can just wait and in time it will correct itself.

**Comment by spartan5v5** [comment]
In other rigs i got 0%-5% seems more real, thanks.

**Comment by UselessGuru** [comment]
> In other rigs i got 0%-5% seems more real, thanks.

If HW is identical you could transfer the 'Stats' folder. This should give you close to identical results (not 100% because polling time for price information at the pool will be different).
