### ISSUE TITLE
Stat file (CcminerTpruvot_Keccak_HashRate) is corrupt and will be reset

### ISSUE THREAD

**Issue by scolarita13** [MultiPoolMiner/MultiPoolMiner#1404]
I am always get this message "Stat file (CcminerTpruvot_Keccak_HashRate) is corrupt and will be reset.
It seems the watchdog for CcminerTpruvot indicates 8 sec, very small comparing with the other miners.

i also get those warnings:
WARNING: Stat file (ClaymoreAmdKeccak40_Ethash_HashRate) was not updated because the value (7975000) is outside fault tolerance (8264084 to 10100547).
WARNING: Stat file (ClaymoreAmdKeccak40_Keccak_HashRate) was not updated because the value (319002000) is outside fault tolerance (330579830 to 404042014).

Any idea what is about?
Thank you,
scolaritaMiner

**Comment by UselessGuru** [comment]
> WARNING: Stat file (ClaymoreAmdKeccak40_Ethash_HashRate) was not updated because the value (7975000) is outside fault tolerance (8264084 to 10100547).
WARNING: Stat file (ClaymoreAmdKeccak40_Keccak_HashRate) was not updated because the value (319002000) is outside fault tolerance (330579830 to 404042014).

ClaymoreAmd miner reports a smaller hash rate than what was detected during benchmark.
Possible reasons;
- modified overclock
- thermal throttling
- benchmark was done with a different  miner version

> I am always get this message "Stat file (CcminerTpruvot_Keccak_HashRate) is corrupt and will be reset.

Solution to both issues: Delete the problematic stat files. MPM will re-benchmark

**Comment by scolarita13** [comment]
Thank you, this made the message to go away. However, maybe it was before but I just notice this:
ClaymoreAmdKeccak40:  KC - Total Speed: 0.000 Mh/s, Total Shares: 12, Rejected: 6
It seems weird: 0 M/h speed 12 shares and 6 rejected.
I have only one AMD card 580. 
Why are so many rejections?
Thank you,

**Comment by UselessGuru** [comment]
> Why are so many rejections

It does not look right, but it is not a MPM issue.
What happens when you run the miner with the exact same command line outside MPM in a CMD window. I am sure you will see the same issue -> Contact either the pool owner or miner developer.

Workaround:
Remove the miner from your config. [Read here / ExcludeMinerName](https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/README.md#command-line-options)
