### ISSUE TITLE
Suggestion Add X16R algorithm and figure out a solution for watchdog

### ISSUE THREAD

**Issue by robl45** [MultiPoolMiner/MultiPoolMiner#1412]
X16R algo so far is fairly profitable, most profitable for the past couple of days on Nvidia for me.  Adding it to MPM should be quite easy as I was able to do it myself.

The real problem lies in the way X16 is done.  It is 16 different algos and the hash rate varies quite a bit.  As it is now I had to take the fault tolerance to + or - 40% and even then I could still lose the miner.  My guess is the quest for asic resistance will lead to more algos like this.

**Comment by UselessGuru** [comment]
> The real problem lies in the way X16 is done. It is 16 different algos and the hash rate varies quite a bit.

The current MPM implementation allows for ONE benchmark result per algo/miner combination.

I have not experimented with X16R, so please excuse my noob question:
As you say some variants are more profitable than others. 
Who/what decides on the variant to mine?
If the variant gets chosen by the pool at miner startup during then how can MPM make sure X16r will be the best algo?

**Comment by robl45** [comment]
Maybe this helps explain it?

https://ravencoin.org/wp-content/uploads/2018/01/X16R-Whitepaper.pdf
The X16R hashing algorithm consists of 16 hashing algorithms operating in chain
fashion with the ordering dependent on the last 8 bytes (16 nibbles) of the hash of the
previous block.

**Comment by UselessGuru** [comment]
> Maybe this helps explain it?

Yes, it does.

I like the technical approach of X16r, but it poses a few tricky challenges for MPM (and similar SW).
a) A simple benchmark is not sufficient as it would only benchmark one sub-algo and the hash rate would not be correct (assuming not all sub-algos are used during ONE bm cycle)
b) Multiple bm runs could be attempted, but then there is no guarantee that a fair sub-algo mix was benchmarked
c) Even with correct overall bm results MPM would need to know what sub-algo is currently being mined so it can calculate profitability
d) The large hash rate fluctuation does not go well with the current MPM hashrate tolerance (watchdog kicks the miner)

**Comment by robl45** [comment]
Currently its one of the most profitable algorithms.  That may change soon, but it definitely should be included and watchdog will need to figure out how to handle it.

**Comment by titvs** [comment]
Well, as of today im also getting x16r kicked by MPM. Will try to disable the watchdog.
Aand strangely i cant seem to be able to benchmark KeccakC with Zergpool...

**Comment by UselessGuru** [comment]
> Aand strangely i cant seem to be able to benchmark KeccakC with Zergpool...

Does is mine OK? Can you run the same command outside of MPM (Copy from log window & paste to CMD window)?

**Comment by titvs** [comment]
> Does is mine OK? Can you run the same command outside of MPM (Copy from log window & paste to CMD window)?

@UselessGuru thats the weird part, the algo/miner doesnt get called to be benchmarked... There's no stat file regarding it...

This is the startup line on the BAT file:

`set "command=& .\multipoolminer.ps1 -wallet **** -username titvs -workername miner01 -region europe -currency eur -type nvidia -poolname miningpoolhub,miningpoolhubcoins,ZergPool,ZergPoolCoins -excludepoolname AHashPool,blazepool,Hashrefinery,ItalYiiMP,NiceHash,YiiMP -algorithm c11,cryptonight,ethash,ethash2gb,equihash,groestl,keccak,lyra2re2,lyra2z,neoscrypt,myriadgroestl,skein,yescrypt,qubit,quark,xevan,X11,x16r,X17,blake2s,tribus -donate 10 -minerstatusurl https://multipoolminer.io/monitor/miner.php -switchingprevention 2 -excludeminername palginnvidia,prospector"`

As you can see i'm only using MPH and ZergPool. I've also noticed that quark and qubit dont seem to be benchmarked either.
Thats odd, KeccakC got benchmarked with Ccminer Tpruvot if i combine MPH and Zpool, but qubit and quark dont get benchmarked either... I wonder if they are disabled somewhere...

Well, ive deleted the logs, the keccakC stat file from the "Zpool benchmark" and switched again to MPH and ZergPool... It doesnt get benchmarked. Neither does qubit and quark.

**Comment by UselessGuru** [comment]
MPM can only benchmark an algo if there is a pool for it. How can you tell???

The [new API](https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1443) will come in handy. DL and replace the three files in the PR.
Then run MPM. Once it starts mining open the file [MPM]\APIDocs.html with your browser. Then click on 'Pools'. Can you find a pool for the missing algo in the API response?

**Comment by titvs** [comment]
> MPM can only benchmark an algo if there is a pool for it. How can you tell???

@UselessGuru Well, the algo is listed at the pool site and it’s being mined, so I guess that’s how you can tell no? :) the algos in question (qubit and quark) aren’t very profitable but since they are supported they should work.
Digging through the miner conf files, I’ve discovered that these particular algos are missing from the supported algos list of Ccminer Tpruvot (and other algos are also disabled for Ccminer Klaust). Is this on purpose? I’ve added them to Ccminer Tpruvot and MPM benchmarked both as it should.
As for KeccakC it gets benchmarked with Zpool but not Zergpool, so i need to dig around a bit more.

Will test the new api as soon as possible and post my results. Keep up the great work!

**Comment by UselessGuru** [comment]
> the algo is listed at the pool site and it’s being mined

Get API working, then upload API result for Miners and Pools. Maybe I can spot the looney.

> Is this on purpose? I’ve added them to Ccminer Tpruvot and MPM benchmarked both as it should.

Yes, There is no point in using all possible algos on all possible miners. The disabled ones are generally superseeded by a faster miner. Feel free to add them at wish.

> As for KeccakC it gets benchmarked with Zpool but not Zergpool,

No idea, should work. Are you using this ZergPool file?
https://github.com/MultiPoolMiner/MultiPoolMiner/blob/9f4ceb7755ab469dcedaada4f7e7e79697144217/Pools/ZergPoolCoins.ps1

**Comment by titvs** [comment]
Nevermind KeccakC @UselessGuru , ive now noticed that I didn’t include it on the Bat file! Geeezz... There are so many configurations and settings that sometimes you get lost.

As for the others algos (quark and qubit) they weren’t benchmarked because they were disabled at the miner config file and no other miner was available for them (I guess). I totally understand that some algos aren’t worth the hassle but if MPM supports them, shouldn’t they be enabled? All this can be made more clear and user-friendly with a GUI were you can select the algos for a specific miner.
All of this is a huge undertaking so I’m in no way criticizing. ;)

Will still test the API though. Thanks!

**Comment by UselessGuru** [comment]
>  All this can be made more clear and user-friendly with a GUI

We're working on it:
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/958
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1187

**Comment by platinum4** [comment]
x16r works fine on your fork I was using it to mine it since Jan 23

**Comment by platinum4** [comment]
@UselessGuru fix/update your fork damnit, it's the best one so far for power draws and split card rigs

**Comment by UselessGuru** [comment]
@platinum4 

> fix/update your fork damnit 👎 

What fixed are so important?

**Comment by UselessGuru** [comment]
> would just try the same thing over and over again if it wasn't working

Simple workaround: Edit the offending miner file and uncomment the algo.

**Comment by robl45** [comment]
Not simple when it's not mining for hours while you at work

**Comment by mtbor** [comment]
Here's some duct tape for you, it's ugly...  Copy the miner file you're using for x16r, rename it, exclude all but X16R by adding hashs in front of them...  Every time it fails based on hashrate, make a new duplicate and rebenchmark..  You'll end up with a range, MPM will try the first one, if it's running that fast, it will work, if not, it will fail and move to the next lowest, and so on, until one catches.

It's sloppy, but at least would ensure that your system continues to mine.

It may be helpful to ensure your interval is not too short, sometimes X16R is slow to reach it's maximum hashrate.

There may be better workarounds..  Just an idea.

**Comment by UselessGuru** [comment]
> Someone please tell me how to add x16r in MPM.

It is supported already, but it does not work with watchdog enabled:
https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/Miners/CcminerTpruvot.ps1
and new:
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1513

**Comment by ParthibanPeriyasamy18** [comment]
@UselessGuru Thank You.  But It seems Tpruvot Not supported x16r(Not sure, But not working for me).  But I Just learned how to add miners in MPM and now added 4 miners(supr, ccminer2.2.5, Nervemore, Nemos of Nervemore).  

Thank You.

**Comment by mtbor** [comment]
Zergpool is the auto exchange pool supporting X16r, if you take the time to
set up a ravencoin wallet, and edit the config.txt file, you can mine on
yiimp.eu with payout to your RVN wallet.

If you have X16r, and have not deleted or excluded zergpool, tpruvot 2.2.5
should mine for you.

On Mar 29, 2018 7:37 AM, "Parthiban Periyasamy" <notifications@github.com>
wrote:

@UselessGuru <https://github.com/UselessGuru> Thank You. But It seems
Tpruvot Not supported x16r(Not sure, But not working for me). But I Just
learned how to add miners in MPM and now added 4 miners(supr, ccminer2.2.5,
Nervemore, Nemos of Nervemore).

Thank You.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1412#issuecomment-377237324>,
or mute the thread

**Comment by ParthibanPeriyasamy18** [comment]
@mtbor Thank you for suggestion

`Below comment Not Related to MPM  -- Please delete If it's not allowed here`

x16r seems good algo. More ASIC Resistance. So  Unlike Bitcoin it's not going to controlled by few ASIC owners.  But the problem is Ravencoin.  It's not listed in any of major exchanges.  Look at what is happening to garlic coin.

**Comment by mtbor** [comment]
Maybe there is a discord channel we could move such discussions to?

**Comment by UselessGuru** [comment]
See https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1682
