### ISSUE TITLE
Suggestion about info shown in resume window

### ISSUE THREAD

**Issue by Falacio** [MultiPoolMiner/MultiPoolMiner#1487]
I think the best way to illustrate what I'm thinking is with an example:

I'm using my laptop to test some algos in 3 pools (MPHCoins, ZergPool and Zpool). A classic resume window could look like this:

https://gyazo.com/4b47a596ec9d0c1b4cfb0f031b0cab2f

As we can see, there are several values for equihash-MPHCoins pair, depending on miner

Some time later, pool info has update and now I have this:

https://gyazo.com/679160e291cee4c753e6046e015df505

Now, I must asume that MPH has lower estimated profit in both algos, but I'd like to really know if that's true, or how much is the difference; and other curiosities like why lyra pool seems to depend on wich pool has been picked for equihash (I've never seen equihash from MPH and lyra from Zerg o Zpool at same time)

What I'm asking about is having also several values for each miner-algo pair, based on pool, so we can contrast that info in "real time". Something like this:

https://gyazo.com/a0e62df308c721790d0d9b2670f60673

In this "screenshot" the values of neoscrypt, phi and lyra are missing for Zpool (they were always lower?), but they should be there, you know what I mean.

I'm pretty sure is something very easy to implement and very informative for any kind of testing

**Comment by UselessGuru** [comment]
> I'm pretty sure is something very easy to implement and very informative for any kind of testing

No, not quite easy to implement due to the very nature of how MPM  works internally.
ONE miner (e.g. DSTM) will internally only be mapped to ONE (the most profitable) pool. You are asking for a ONE to MANY construct which is not available.

Feel free to dig through the data available through MPM's API on http://localhost:3999/ and create you own script to create your requested summary. Of particular interest will be:
http://localhost:3999/activeminers
http://localhost:3999/allpools
