### ISSUE TITLE
Monitoring does not works

### ISSUE THREAD

**Issue by Rokk001** [MultiPoolMiner/MultiPoolMiner#1526]
Hi
Your monitor has a isue:
https://multipoolminer.io/monitor/?address...

Algos with 0 Hash Speed are listed and the monitor is showing them as they are generating balance.
Its showing too much btc/day incoming...

Regards

**Comment by grantemsley** [comment]
The monitoring is working fine, I believe you are just misinterpreting the results.  I can't see your actual info though since the URL you posted is cut off and doesn't include your address.

The BTC/day is always an estimate based on your benchmarked speeds.  Since the actual live speed is only updated once every few minutes, and because it will sit at 0H/s for quite awhile even though it's still mining before the program can get the actual speed, this is the best way to calculate it.  Otherwise the BTC/day value would fluctuate wildly when switching between miners.

And the estimates are just that - estimates.  They will never be perfectly accurate,

**Comment by Rokk001** [comment]
Hi

Here is my url:
https://multipoolminer.io/monitor/?address=1309d8be-51e0-45d1-b925-ab8b0e8f49f8&showdetail=yes

as you can see, its adding incomming from algos with 0 current speed.
something is wrong

regards
Mario

2018-03-30 20:37 GMT+02:00 Grant Emsley <notifications@github.com>:

**Comment by Rokk001** [comment]
I think you are calculating wrong BTC/day, I think BTC per day must be only
algos with current speed and not all values in monitoring.

2018-03-30 21:48 GMT+02:00 M Z <mario.ziv@gmail.com>:

**Comment by grantemsley** [comment]
Ok, I see what you are getting at now.  I will take a look at it.

**Comment by mkirov0** [comment]
I have seen this issue before. It happens to me when there is a failed miner. Restarting MPM fixes it, but I know its not the preferred method...
