### ISSUE TITLE
2.7.2.7: issue trying to disable algos in ahashpool

### ISSUE THREAD

**Issue by amolitor** [MultiPoolMiner/MultiPoolMiner#1559]
Heya there, been trying to disable some algos on ahashpool without any luck, heres the part of ahashpool at my config.txt:
Even tried with case sensitive
-------
"AhashPool": {
      "BTC": "mywallet",
      "Worker": "$WorkerName",
      "DisabledAlgorithms": ["bitcore","Bitcore","nist5"]
    }
-------
Thanks.

**Comment by aaronsace** [comment]
The readme says it is `ExcludeAlgorithm` not `DisabledAlgorithms`...?

**Comment by UselessGuru** [comment]
> i followed these instructions:
> https://github.com/MultiPoolMiner/MultiPoolMiner/blob/d32b3ac5c1f563fecacd6c08368d73fa73182aad/README.md

You are referring to information that has not commited yet [PR is still pending] (https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1435) because there might be some issues with it.. 

These commands only work if you all the other files that go with it. Otherwise use ExcludeAlgorithm as aaronsace suggests.

**Comment by mkirov0** [comment]
Yeah, what @UselessGuru said

**Comment by amolitor** [comment]
ohhh i see, well i made it work changing those lines anyway :) 
But thanks you all for the feedback.
