### ISSUE TITLE
Coins stuck on auto exchange

### ISSUE THREAD

**Issue by kingprawn77** [MultiPoolMiner/MultiPoolMiner#1572]
Hi,
Had Maxcoin & Monero "stuck" in auto exchange for a couple of months, everything else is OK.
Can you free up, please?

Thanks

**Comment by mkirov0** [comment]
MPM does not actually hold any crypto. It is all up to the pool you should contact them. Most pools would wait until they have a good amount of certain coin before they move it to an exchange because of fees. I don't know if its a viable option but you can start mining this coin until a sufficient amount is mined to be moved and exchanged; or you can just wait.

**Comment by kingprawn77** [comment]
I wish it was as easy as that I have 18 coins, I wish it was BTC lol
I have no idea how to contact them, have you an email address?

**Comment by mkirov0** [comment]
Do you know which pool we are trying to contact?

**Comment by kingprawn77** [comment]
It’s the mining pool hub

**Comment by mkirov0** [comment]
You can use these to contact them:

<img width="331" alt="screen shot 2018-04-10 at 9 03 33 pm" src="https://user-images.githubusercontent.com/28104701/38574931-c984167c-3d02-11e8-8437-61438aa9cf47.png">

If you want to use the links you can also find them on the front page (MPH) lower right part of the page.

**Comment by kingprawn77** [comment]
Thanks for that 😊
