### ISSUE TITLE
Stat file is corrupt and need to be reset

### ISSUE THREAD

**Issue by thinkplaystudios** [MultiPoolMiner/MultiPoolMiner#1573]
I constantly get these:
`WARNING: Stat file (ClaymoreAmdBlake2s30_Ethash_HashRate) was not updated because the value (150279000) is outside fault tolerance (162683255 to 198835090).
WARNING: Stat file (ClaymoreAmdBlake2s30_Blake2s_HashRate) is corrupt and will be reset.`

Any idea?  Let me know if you need me to include log files.

Thanks,

**Comment by grantemsley** [comment]
Basically it means the miner isn't performing to what the benchmarking said it should, +/- a certain percent.  If it's happening on a regular basis, you need to rebenchmark.  Run `ResetBenchmark.bat` and restart the program.

It can happen if:

- Stat files get corrupted (due to crashes, power failures, etc)
- Performance of your card(s) has changed significantly - you've added or removed card, or some aren't working properly
- You've updated to a new version with new miners that perform differently and tried to skip benchmarking by copying your old stats folder.
- You were overclocked when benchmarking and your overclock isn't being applied anymore.  Or you change your overclock settings.
- Your system is running slow for other reasons (someone is using it, background programs, viruses, what have you) and it's affecting the miner performance.
- The computer gods frown upon you (seriously, sometimes it just happens even if you changed nothing...rare, but it happens).

Just rebenchmark and all should be fine.

**Comment by thinkplaystudios** [comment]
This helps me confirm my findings, thanks!  What's been happening is one or more of the GPUs crash when MPM switches to a different algo.  I think it is force-closing the miners and causes GPU crashes.  I've set it up where when a GPU crashes, it re-applies the overclocking (core/clock).  This warning has since stopped.  Thanks again.

**Comment by grantemsley** [comment]
There is a fix for that!

Add `-delay 10` to your start.bat along with the other parameters.  That will make it wait 10 seconds between stopping old miners and starting new ones.  That gives them time to release whatever video card resources they are holding on to and avoid crashes.

**Comment by thinkplaystudios** [comment]
Ok I'll try that, thanks!  I had it set to 6 secs as that's what I gauged it took to reset and clear the video memory, but maybe there's more I'm not seeing behind the scenes.  I'll report back on the next restart with this setting.

**Comment by thinkplaystudios** [comment]
So far, cards still randomly crash and reset even with the longer timeout.  From my observation (log files, event log, monitoring tools), it's consistent with MPM switching to a different miner and it shuts down the current miner (maybe forcefully), and thus causing one or more of the GPUs to crash.

**Comment by UselessGuru** [comment]
Crashes can have many causes. Yours sound like HW issues. Maybe your power supply is too weak or you overclock too much..
MPM is just stopping/starting miners based on profit. If your system crashes then MPM can not really do anything about it. Algorithm/miner switching is never the true reason for crashes.

**Comment by thinkplaystudios** [comment]
Agreed, MPM is not the direct cause.  I'm just trying to tweak it to where I can control the crashes.  As an example, when running ethminer.exe directly (no MPM) and I just close the window (rather than ctrl-c and wait for shutdown), highly likely one of the cards will crash.

**Comment by zryder94** [comment]
"I've set it up where when a GPU crashes, it re-applies the overclocking (core/clock). This warning has since stopped. Thanks again."
 How did you go about this?

**Comment by thinkplaystudios** [comment]
Use HWInfo64 alerts which call scripts that re-apply the OC settings.

**Comment by thinkplaystudios** [comment]
@UselessGuru You were right, two of the GPUs had switched VBIOS configs and was causing crashes when specific miners were closed because they never quite unloaded.  Not wanting to leave some options unturned, I went and investigated, and I discovered VBIOS settings were flipped between the two cards.  Thanks!
