### ISSUE TITLE
Nvidia and AMD in same rig

### ISSUE THREAD

**Issue by thinkplaystudios** [MultiPoolMiner/MultiPoolMiner#1586]
Hi guys, this is more of a question than an issue:

Can I run one instance of MPM, set it up for both AMD and Nvidia, and will it run simultaneous miners specific to the GPU type?  Currently, the rig I'm testing MPM with only has AMD, but I'm now looking to test it on a mixed rig setup.

Can you guys share your experience with this setup?

Thanks,

**Comment by symalla** [comment]
I am running 1 rig with 6 AMD and 4 Nvidia. One instance of MPM properly runs AMD miner and Nvidia Miner instances at the same time.

**Comment by grantemsley** [comment]
Yes.  If you have one AMD and one NVIDIA card, it will run separate miners on each card (or one of the dual platform miners if you have those enabled).

This is actually my preferred setup, since mixing different versions of NVIDIA cards in a system can hurt performance since it just runs one miner for all cards, which works fine for some miners but not so well for others.
