### ISSUE TITLE
Price out of sync bug

### ISSUE THREAD

**Issue by angelics** [MultiPoolMiner/MultiPoolMiner#1620]
i tried to discuss this in #1435 without raising issue and make a PR. there is previous log and SS in there.

[Logs.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1976408/Logs.zip)

the log is from fresh master. i have nth altered except commenting out ASIC algos in miners files, changed switching prevention to 1 and use only ccminer variants.

to temporary solve MPM to switch to less profitable algo during the price-out-of-sync phase:
comment out multipoolminer.ps1 line 294, 295, remove line 297 else { line 300 }

**Comment by grantemsley** [comment]
Usually the prices out of sync error happens when a pool isn't responding properly - in which case we usually do want to switch to the next best, since that pool may be having issues.

To figure out exactly what's going on, it would be useful to see the pool list.  Can you run it, and when it complains about the pool prices being out of sync, go to http://localhost:3999/pools in a browser and post the output from that?

**Comment by angelics** [comment]
i'll have a test again when i get extra spare time for my test rig. will report back

it is nvr an issue when mining single pool. the price will b properly sorted even if the pool api is down.

on my last test, downloading and installing powershell through downloader broke environmental variable. it was fine with 6.0.2.
if u install preview manually , u'll notice that they added new tickboxes for environmental variable. it might b broken somewhere. i had to manually fix the proper environmental variable path for pwsh.
