### ISSUE TITLE
Alexis78-v1.1/ccminerAlexis78-v1.1.7z not tidied up

### ISSUE THREAD

**Issue by mserpell** [MultiPoolMiner/MultiPoolMiner#1727]
Since the latest update ,I keep getting "Acquiring Online (https://github.com/nemosminer/ccminerAlexis78/releases/download/Alexis78-v1.1/ccminerAlexis78-v1.1.7z)" in the blue box on the main screen; it does not get removed at all when running "start.bat" session.

![untitled](https://user-images.githubusercontent.com/5593748/40078924-76bd9296-58c9-11e8-9bb3-9d713016d818.png)

**Comment by mkirov0** [comment]
Did you download a fresh copy or just added the miner file to the Miners folder?
I am asking since this happened to me when I just added the miner. I fixed it by deleting all the traces from the previous version (ccminerhsr) deleted the stats and the contents of Nvidia-Alexis78hsr. Then I restarted MPM and it all went well.

**Comment by mserpell** [comment]
Thanks for the quick response.  I might try the approach you undertook to correct the issue. Can you please provide the specific actions as I'm not that familiar with how to do this.

**Comment by mkirov0** [comment]
This is what I did:
close MPM
add CcminerAlexis.ps1 to the Miners folder
delete this file - /Bin/Miners/CcminerHsr.ps1
delete this folder - ./Bin/Nvidia-Alexis78hsr
(Optional) delete - all files with ccminerHsr in the filename in the Stats folder
there shouldn't be any but check for files with ccminerAlexis in the filename and delete them if you find any

**Comment by mserpell** [comment]
that worked, thanks for your help.
