### ISSUE TITLE
Stopped working no pools available

### ISSUE THREAD

**Issue by robl45** [MultiPoolMiner/MultiPoolMiner#1737]
Since this afternoon, it just says no pools available.  Was using zergpool, hashrefinery and mining pool hub.  Has been working flawlessly for months.

Tried useless guru version,s ame thing.  Awesome miner appears to work fine.

**Comment by robl45** [comment]
Tried adding all other pools to see what happens.  Ahash pool is working.   The others just say api failled over and over.

**Comment by robl45** [comment]
Tried newest version to see and same thing, all saying api failed.

**Comment by robl45** [comment]
Works fine going to the api.   Why does ahash and blaze pool work?

**Comment by hollon21** [comment]
I have this exact same problem. Internet connection is fine. My other miners running MPM are running fine on the same connection. 1/5 miners does this for no obvious reason. Sometimes restarting it will fix it, but that is only temporary.

I tried redownloading and using a fresh version--same problem. Other miners that I used in the past work fine on this computer (bminer, ccminer, etc.). Any ideas? Will be attaching a recent log that shows it working then mysteriously stop working. If any other files needed let me know
[MultiPoolMiner_2018-05-18.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2017775/MultiPoolMiner_2018-05-18.txt)

**Comment by hollon21** [comment]
Here are some more logs from the same miner


[MultiPoolMiner_2018-05-18_09-44-53.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2017778/MultiPoolMiner_2018-05-18_09-44-53.txt)
[MultiPoolMiner_2018-05-18_09-41-17.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2017779/MultiPoolMiner_2018-05-18_09-41-17.txt)
[Eminer-8550_2018-05-18_09-39-34.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2017780/Eminer-8550_2018-05-18_09-39-34.txt)
[MultiPoolMiner_2018-05-18_09-10-54.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2017781/MultiPoolMiner_2018-05-18_09-10-54.txt)

**Comment by grantemsley** [comment]
`PS>TerminatingError(Invoke-RestMethod): "The operation has timed out."`

Means you are having network issues.  Could be faulty network card, ISP problems, router problems, or being banned by cloudflare (cloudflare is really picky...there are plenty of ways to trip it where visiting the URL in a normal browser will still work, but automated requests won't).

As your edits above say, your problem is likely your wifi adapter/connection.  I recommend using ethernet if at all possible, since that is more reliable and lowers latency.
