### ISSUE TITLE
ethminer 0.15.0rc2

### ISSUE THREAD

**Issue by borzaka** [MultiPoolMiner/MultiPoolMiner#1919]
[ethereum-mining/ethminer](https://github.com/ethereum-mining/ethminer/releases)

0.14 and above has different command line options: [POOL_EXAMPLES_ETH.md](https://github.com/ethereum-mining/ethminer/blob/master/docs/POOL_EXAMPLES_ETH.md)

from: https://ethereum.miningpoolhub.com/
> a. (0.14 above)
> 
> NVIDIA
> 
> ethminer -U -P stratum2+tcp://username.workername:x@us-east.ethash-hub.miningpoolhub.com:20535
> 
> AMD
> 
> ethminer -G -P stratum2+tcp://username.workername:x@us-east.ethash-hub.miningpoolhub.com:20535

**Comment by angelics** [comment]
refer #1748 and make a pr

**Comment by borzaka** [comment]
The latest non-final version is [ethminer 0.14.0](https://github.com/ethereum-mining/ethminer/releases/tag/v0.14.0)
Currently the v0.13.0 is included in MPM

**Comment by UselessGuru** [comment]
I am working on implementing 0.14

**Comment by Spudz76** [comment]
Note their new URL styled format does not allow for Dwarfpool (and likely some others) worker-named logins such as `0xWalletid/workername:password-or-email`

Because the extra slash is not parsed as part of the login.  So I am still using the old arguments format, and they still work until they fix that parsing problem.  And likely another problem with multiple `@` in the string but I use `x` and don't bother with email alerts (the only reason to pass an email-as-password)

**Comment by UselessGuru** [comment]
@Spudz76 

You will need to use something like

`Arguments  = ("--api-port -$Miner_Port -P $($Protocol)://$([System.Web.HttpUtility]::UrlEncode($Pools.$Algorithm_Norm.User)):$([System.Web.HttpUtility]::UrlEncode($Pools.$Algorithm_Norm.Pass))@$($Pools.$Algorithm_Norm.Host):$($Pools.$Algorithm_Norm.Port)$($Commands.$_)$CommonCommands --cuda --cuda-devices $(($Miner_Device | ForEach-Object {'{0:x}' -f ($_.Type_Vendor_Index)}) -join '')" -replace "\s+", " ").trim()`

**Comment by UselessGuru** [comment]
Available for testing in https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1960
