### ISSUE TITLE
multiple instances

### ISSUE THREAD

**Issue by sibuminer** [MultiPoolMiner/MultiPoolMiner#1924]
trying to split my mining rig into running 2 instances because alexis-forks having hard time starting all 12 gpus.
1st instance with first six card, 2nd instance with last six
tried below:
2 different copy of MPM, in 2 different directory.
whenever the 2nd instance of MPM start a new miner, 1st instance of miner killed off.
changed api port(default+1) of 2nd instance
using latest release

running fine using single instance. please close this if this is consider not an issue.
currently using 300 interval and switchingprevention 4 to "fix" alexis fork slow start
version 3 looks very promising. 
thanks

**Comment by UselessGuru** [comment]
> 1st instance of miner killed off

Out of the box you cannot run two instances of MPM.
Culprit for the killing is line 578:
`    if ($ActiveMiners | ForEach-Object {$_.GetProcessNames()}) {Get-Process -Name @($ActiveMiners | ForEach-Object {$_.GetProcessNames()}) -ErrorAction Ignore | Select-Object -ExpandProperty ProcessName | Compare-Object @($ActiveMiners | Where-Object Best -EQ $true | Where-Object {$_.GetStatus() -eq "Running"} | ForEach-Object {$_.GetProcessNames()}) | Where-Object SideIndicator -EQ "=>" | Select-Object -ExpandProperty InputObject | Select-Object -Unique | ForEach-Object {Stop-Process -Name $_ -Force -ErrorAction Ignore}}`
In any case you will need to do the api port change.

**Comment by grantemsley** [comment]
And the reason for the killing is that sometimes the miners don't actually close when they are told to - so you end up with several miners all trying to use the same gpus and either going slow or crashing.  So it's pretty important.

Which specific miner(s) are causing you the problems?  If the problem is they don't work well across that many cards at once, we can probably modify them to start separate copies for each GPU, or every group or 6 or whatever works.
