### ISSUE TITLE
Monitoring log hangs .

### ISSUE THREAD

**Issue by harssh** [MultiPoolMiner/MultiPoolMiner#1957]
<img width="1018" alt="screen shot 2018-07-06 at 3 31 30 pm" src="https://user-images.githubusercontent.com/2812994/42399559-e332d32c-8133-11e8-9731-9e0f028d94bf.png">

Specially during benchmarking the logging screen hangs the miner keeps on running. 
But no update happens.
Happened more than three times a day so thought should create a issue.

Above screenshot miner and logger are half hour apart.

**Comment by grantemsley** [comment]
Is the actual script window, where it shows the tables of all the miners and such updating, or is it stuck too?

I've seen the script get stuck at getting miner information a few times on one of my machines, but I've never been able to figure out what's causing it to hang there, and it's tough to pin down because sometimes it will run for days without issue then do it over and over for an hour.  If I had a way to consistently make it break it would be a lot easier to fix.

**Comment by harssh** [comment]
Yes the window which had all miners listed was also stuck.

**Comment by grantemsley** [comment]
Is it still happening?  Were any of the same miners running each time?

If we can find a way to reliably trigger the problem I can probably fix it.  I just haven't been able to so far.

**Comment by harssh** [comment]
Yes miner was same its ccminer running Lyra or Skein algo.

**Comment by grantemsley** [comment]
Can you zip everything in your logs folder and upload it for me?  I will take a look and see if it gives me any more insight.

**Comment by grantemsley** [comment]
@UselessGuru in my case, I'm certain it wasn't from selecting anything.  The system was locked and running fine for hours before that.  And it's always while loading the miners, nowhere else.
