### ISSUE TITLE
Accuracy in % in pwsh.exe extreme low

### ISSUE THREAD

**Issue by m-bosch** [MultiPoolMiner/MultiPoolMiner#2015]
Hi All,

Hopefully more people have this issue, the accuracy of the miners and their speed/sub are extremely low, seems like it decreases every day.

Today my average will be a low 70% but I have some with MINUES 235%..... AND many of 63%.

Are there steps to do for me to solve this. Because of this issue my miner is mining less profitable alto's....

**Comment by m-bosch** [comment]
Hi Grant, isnt it a good suggestion to run that frequently just to lower the damage? like every 24/48hrs, maybe equal to the donation? This way the do action will better also

**Comment by grantemsley** [comment]
No, because keeping those stats also helps protect you from switching to very short spikes that you won't actually profit from

**Comment by m-bosch** [comment]
Ok now I tried to set the switch prevention to 4 just not to switch every 2 minutes but it won't help a lot.

**Comment by m-bosch** [comment]
hi @grantemsley the profit is there for few days now, but it is not getting better...

<img width="726" alt="image" src="https://user-images.githubusercontent.com/16580113/43267860-5c0da9f0-90ef-11e8-91e7-3918317f2ede.png">


i also get MANY (1 of 4or 5) notifications of the following: 

2018-07-26 16:15:02 WARNING: Stat file (CcminerNevermore_HSR_HashRate) was not updated because the value (30076867) is outside fault tolerance (20542206 to 25107141). 

it is not only on this many but on many. I did notice it is most of the times HSR, Bitcore, X17 & Timetravel

**Comment by UselessGuru** [comment]
@m-bosch 

You are mixing things here. :-)
Accuracy is impacted by the price fluctuation as provided by the pool. This was the original post.

What you are now reporting is about a mismatch of benchmark speed and measured mining speed.

> WARNING: Stat file (CcminerNevermore_HSR_HashRate) was not updated because...

messages are displayed when the stored speed in the stat file don't match the retrieved speed from the running miner. For some miners this is normal because they take a while until they report fair speed.
Then there are the notorious algorithms with fluctuating hash rates, e.g. X16R & x16s. It in their nature to report wildly varying speed.
Yet others are caused by a driver change, change of overclock, or faulty benchmark results.

You can always re-benchmark the problematic miners - just delete the corresponding stat file.

It will also help if you lengthen the interval time to maybe 2-5 minutes.

**Comment by m-bosch** [comment]
sorry for the mixed topics. 

I thought it both had to do with the wild mixes of miners that are getting launched. Miners that I think that would be very profitable. I will increase interval

**Comment by grantemsley** [comment]
Increasing the interval will cause you more problems than it solves.  I don't recommend changing it.

**Comment by m-bosch** [comment]
i set the interval to 70sec. and the prevention to 5. removed the stats from the HSR, Bitcore, X17 & Timetravel -algo's and now rebenchmarking some.
