### ISSUE TITLE
Miner Earnings estimate per day sometimes gets exaggerated by Pool over estimates

### ISSUE THREAD

**Issue by paulpoco** [MultiPoolMiner/MultiPoolMiner#2077]
![image](https://user-images.githubusercontent.com/801414/43923855-cb06f26a-9bd7-11e8-8c63-bc1d9e3d4c5d.png)

![image](https://user-images.githubusercontent.com/801414/43923870-dcc344fe-9bd7-11e8-9a58-553539e95e52.png)
![image](https://user-images.githubusercontent.com/801414/43923882-ecbbde5c-9bd7-11e8-98ee-f608afcdf25e.png)

The 24hr Estimate is almost 100x bigger that Current of 24hr Actual.  There is probably a problem with the pool?

**Comment by UselessGuru** [comment]
> The 24hr Estimate is almost 100x bigger that Current of 24hr Actual. There is probably a problem with the pool?

Yes. MPM uses the current estimate for YiiMp based pools.

**Comment by grantemsley** [comment]
Sometimes a pool will hit a few successful blocks all in a row, making it look ridiculously profitable for a bit.  That's why we use the current estimate and average things out as best we can to get more realistic estimates.

But in the end, they're all estimates - we can't predict which pool is going to get the next block for a particular coin any more than you can tell what the lottery numbers for next week are going to be.
