### ISSUE TITLE
Pool prices out of order.

### ISSUE THREAD

**Issue by Byrd1083** [MultiPoolMiner/MultiPoolMiner#2096]
I have 3 rigs going. all compiled identical with master and up to date algo files. I have all systems set to interval of 3600. For some reason my 12 gpu rack keeps getting the pools prices all mixed around. It is a problem that seems to keep coming back on this machine. If I shut down MPM and just restart it, it will temp fix the issue and all profitability looks correct. but after an hour it reassembles all the prices out of order. Any help is much appreciated on this issue. I'm posting my screen shot of my MPM window to prove it. Also the cpu profits will disappear and reappear randomly as well. Something the other 2 rigs never do.
[Multipool_Window.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2314825/Multipool_Window.txt)

**Comment by Byrd1083** [comment]
FYI, I have tried to reset profitability as well. It will work for a while and eventually go back to this chaos. I've yet had a full day of mining without this happening.

**Comment by Byrd1083** [comment]
So if RVN is giving me like $20+ a day and is super profitable right now, why would it mine sib which is on the bottom of the list? That makes no sense to me.

**Comment by Byrd1083** [comment]
Also that answer does not explain why 2 of 3 rigs do not do this. They have all been running the same time, started at the same time with the same hardware. Yet this 1 rig will not hold the prices in order. So one machine is a bias machine?

**Comment by Byrd1083** [comment]
I do notice that when I reset the profit, Sib always comes up incorrect profit. Says like $200000 or some other ridiculous number. It will start mining it immediately. So saying that it is bias, Is there a possibility that when I reset the profit and it records that ridiculous number, it is bias towards sib? But that still doesn't explain why 2 of my 3 rigs do not have this problem. I can walk up to them right now, turn the monitor on and see a correct list of prices.

**Comment by Byrd1083** [comment]
FYI, all 3 rigs are set 2 -interval 3600. 2 of them do not have this problem and have been running for a few days so I would like a better fix for this then just saying it is the interval.

**Comment by Byrd1083** [comment]
Here is output for 1 of those other rigs I have not having this problem. It is a 1 gpu test rig. I guess it is not bias.
[test-rig.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2315008/test-rig.txt)

**Comment by Byrd1083** [comment]
Just to prove, here is 3rd log from my 5 gpu rig-2 output. No bias here.
[rig-2.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2315034/rig-2.txt)

**Comment by Byrd1083** [comment]
Update. I am not sure if this is fixed or if this issue should be closed but earlier I reset, left and came back to find that the 12 gpu rig is now holding proper values even with - interval 3600. Earlier when I left, the only change I made was I restarted all 3 at the same time but deleted the algo "sib" from each start.bat

This could be an error with that algo. Should be looked at it reporting incorrect values somehow /sometimes creating logical errors in profit switching.

**Comment by UselessGuru** [comment]
> This could be an error with that algo. 

No.
The issue that you are seeing is always caused by the data supplied by the pool.
MPM keeps an accumulated list of all algorithms you can mine and the pricing information for each pool.

Lets say you are using 5 pools:

- on first run MPM contacs the 5 pools and receives 20 algos per pool (just to keep things simple).
MPM will now have an internal list with 100 (5 x 20) available algos, each has a currenz time stamp. 
You can display this collection with [http://localhost:3999/allpools](http://localhost:3999/allpools)

- On the next run MPM contacts all the pools again and receives the same 20 items again. MPM will update the prices and time stamps for all 100 items.

- On one of the subsequent runs one of the pools add 5 new algorithms and send 25 (20 + 5new) algos.
MPM will now have 105 algos to mine, all with current time stamps

Now we come to the crucial thing:

- on one of the next runs one pool only lists 10 instead of 20 items.
MPM can update the timestamp only on 95 items, 10 items keep the old timestamp -> prices are out of sync.
They stay out of sync until the pool is re-sending the missing 10 algorithms, or until you restart MPM.

Its important to understand that the pools constantly update the data available through their API. This is beyond MPMs control.
