### ISSUE TITLE
Resetting clocks after Claymore exits

### ISSUE THREAD

**Issue by jweber018** [MultiPoolMiner/MultiPoolMiner#2104]
Hey folks, looking for some advice here. My NVIDIA 1070 cards can mine Eth stable at +450 memory clock, but they crash when running any fork of CCMiner (MPM switches to CCMiner, it crashes and I lose hashes). Is there a way I can make MPM run a script after Claymore closes?

Note: I have the clocks set to +250 in Afterburner (which is stable for CCMiner) and Claymore set with -mclock.

Thanks in advance.

**Comment by UselessGuru** [comment]
Running custom scripts before or after is not (yet) supported.

I personally believe that you overclock too much. I overclock my cards my self, and I can switch between any miner/algo without any issues. Overclocking memory to the max is actually reducing overall speed because the GPU spends more time correcting memory errors,

**Comment by jweber018** [comment]
Could be, I'll try lowering the clocks a bit. Would be a really cool feature tho, I'll contact Claymore too, he could implement it for his miner (in fact, PhoenixMiner does reset GPU clocks on exit, but does not support -mclock on NVIDIA 👎 )
