### ISSUE TITLE
What can you do with the Miner section of config.txt?

### ISSUE THREAD

**Issue by paulpoco** [MultiPoolMiner/MultiPoolMiner#2231]
It would be cool to have it set that a certain Miner without having to type in the version number, that Miner wouldn't ever try and do a certain Algo?

I could find anything in the Readme about the Miner section of config.txt.

Like I might want to not use the bottom 3 miners ever, would save time on benchmarking.
![image](https://user-images.githubusercontent.com/801414/48239381-81a38b80-e383-11e8-883d-7e204f36b8d1.png)

**Comment by UselessGuru** [comment]
The version number is in the miner name so it does trigger the benchmark because new versions will produce different hash rates and this is an easy way to have accurate hashrates.

Currently there is no config setting for what you want. But you can disable the algo in the miner file directly (just comment them out by inserting a #)

What would be a meaningful setting in the miner section to achieve what you want?

**Comment by paulpoco** [comment]
"MinerAlgoDisable"
         "X16R"
                 Miner1
                 Miner2
                 Etc
