### ISSUE TITLE
Nicehash StablePrice should be Day instead of Week in Pool file?

### ISSUE THREAD

**Issue by paulpoco** [MultiPoolMiner/MultiPoolMiner#2234]
currrently "StablePrice   = $Stat.Week"	        vs                "StablePrice   = $Stat.Day #instead of .Week"

**Comment by UselessGuru** [comment]
> currrently "StablePrice = $Stat.Week"	vs "StablePrice = $Stat.Day #instead of .Week"

What's the benefit?

**Comment by aaronsace** [comment]
Day is worse than week; it's meant to be a base line not a daily ticker. Even NiceHash has fluctuation problems (that can actually be worse with crazy buyers sometimes) even though it's the most reliably accurate figures due to it not being a real mining pool. It is about predicting the future not what the API says the payout is at a single point in time.

**Comment by aaronsace** [comment]
What is not measured is the accuracy of the estimated payout figures from the API which seems to be what you are trying to compensate for. It's not related to the current calculations. The way to measure this across pools consistently is difficult and may create inaccurate biases. A starting point may be to look at the Zpool API which shows both actual payout and estimated payout over a 24 hour period.
