### ISSUE TITLE
Creating miner config files failed

### ISSUE THREAD

**Issue by smarcello** [MultiPoolMiner/MultiPoolMiner#2440]
getting:
2019-11-07 21:55:33 ERROR: Creating miner config files failed (XmrigCryptonight-v2.14.4-CPU-1xAuthenticAMD3CoreCPU-1 {CryptonightR@}) [Error: 'Method invocation failed because [System.Management.Automation.PSObject] does not contain a method named 'op_Multiply'.'].

**Comment by UselessGuru** [comment]
Do you have more detailed information in the log file?

What is your exact config? Please port your start file and config.txt.

Thank you!

**Comment by UselessGuru** [comment]
@smarcello 

Do you have an update?

**Comment by smarcello** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Nope sorry, logs have been erased and it didn't happen AGAIN!                                                                                                                                              Inviato con Posta in arrivo di BlackBerry Hub+ per Android                                                                                                                                                                           Da: notifications@github.comInviato: 17 novembre 2019 11:46 AMA: MultiPoolMiner@noreply.github.comRispondi a: reply@reply.github.comCc: semel13@gmail.com; mention@noreply.github.comOggetto: Re: [MultiPoolMiner/MultiPoolMiner] Creating miner config files failed (#2440)  @smarcello
Do you have an update?

**Comment by UselessGuru** [comment]
@smarcello 

I found the root cause of your problem. It is fixed with this change:
https://github.com/MultiPoolMiner/MultiPoolMiner/blob/07d7ac8b9d044b2a12c8653788f177fa642f045c/APIs/Xmrig.ps1

To get your computer mine XmrigCryptonight-v2.14.4-CPU properly you'll need to
- delete the `Config-*` & `ThreadsConfig-*` files in the '`Bin\XmrigCryptonight-v2.14.4-CPU`' folder.
- delete all '`Stats\XmrigCryptonight-v2.14.4-CPU-*.txt`' files.
