### ISSUE TITLE
prefered coin

### ISSUE THREAD

**Issue by boysie123** [MultiPoolMiner/MultiPoolMiner#35]
is there a way to set a preferred coin?

By this I mean say you exchange all your mining pool side to ETH there is an over head to converting say 2-5% so if ETH was with in this range of mining directly would it not be best to just default to this coin and avoid the conversion costs which could actually make mining another coin less profitable esp if there is very little in the difference.

You could set the % and the coin at run time. and I expect you could just add it to the already accepted calculations of the BTC per day?

Boysie

**Comment by buntakunfumoffu** [comment]
hi, is it also possible to subtract the cost of electricity by algorithm in btc.

**Comment by aaronsace** [comment]
It can get quite complicated trying to calculate the losses. Will look into the idea.

**Comment by boysie123** [comment]
it can be option data for sure, eg how much watt is this algo using to get this sort of hash rate and the constant of your real world cost in $ (mine is in £ but $ would be fine) when talking profit power is massive part of it and having the option to add this data in would be very nice indeed. but also to have an understanding that conversion is not free from 1 coin to another.

**Comment by aaronsace** [comment]
Ah, yes, currency conversion is a definite. Once I've fixed some issues I'll look into this.

**Comment by lyolyalya** [comment]
aaand one thing=)can you add the feature that show us mining coin currently?not just algo?

**Comment by aaronsace** [comment]
I can, will look into displaying it somewhere.

**Comment by lyolyalya** [comment]
would be nice, thanks

**Comment by lyolyalya** [comment]
hey...i have some doubts about miningpoolhub profitability page...
i look at diff of digibyte skein which was 985 and with what to mine it gives me about 8 dollars per day with 1660 mhs. at 0.00000030 btc with 870 $
then i look at myraid-skein diff and it was 635.with the same hashrate i must earn about 4.84 dollars at 0.00000025 btc with 870 $.you can recalculate this items if you want on whattomine to ensure...so here the question.why i mine myraid-skein instead of digibyte?
i use https://miningpoolhub.com/index.php?page=api&action=getautoswitchingandprofitsstatistics to ensure...and what i get - 
{"success":true,"return":[{"algo":"Cryptonight","current_mining_coin":"monero","host":"us-east.cryptonight-hub.miningpoolhub.com","all_host_list":"us-east.cryptonight-hub.miningpoolhub.com;europe.cryptonight-hub.miningpoolhub.com;asia.cryptonight-hub.miningpoolhub.com;hub.miningpoolhub.com","port":12024,"algo_switch_port":17024,"multialgo_switch_port":12024,"profit":1731.67427377},{"algo":"Equihash","current_mining_coin":"zclassic","host":"us-east.equihash-hub.miningpoolhub.com","all_host_list":"us-east.equihash-hub.miningpoolhub.com;europe.equihash-hub.miningpoolhub.com;asia.equihash-hub.miningpoolhub.com;hub.miningpoolhub.com","port":12023,"algo_switch_port":17023,"multialgo_switch_port":12023,"profit":3924.6936296},{"algo":"Sia","current_mining_coin":"siacoin","host":"hub.miningpoolhub.com","all_host_list":"hub.miningpoolhub.com","port":12022,"algo_switch_port":17022,"multialgo_switch_port":12022,"profit":0.0004484},{"algo":"Yescrypt","current_mining_coin":"myriadcoin-yescrypt","host":"hub.miningpoolhub.com","all_host_list":"hub.miningpoolhub.com","port":12021,"algo_switch_port":17021,"multialgo_switch_port":12021,"profit":130.36224759},{"algo":"Ethash","current_mining_coin":"ethereum","host":"us-east.ethash-hub.miningpoolhub.com","all_host_list":"us-east.ethash-hub.miningpoolhub.com;europe.ethash-hub.miningpoolhub.com;asia.ethash-hub.miningpoolhub.com;hub.miningpoolhub.com","port":12020,"algo_switch_port":17020,"multialgo_switch_port":12020,"profit":0.04914084},{"algo":"Blake-Vanilla","current_mining_coin":"vcash","host":"hub.miningpoolhub.com","all_host_list":"hub.miningpoolhub.com","port":12019,"algo_switch_port":17019,"multialgo_switch_port":12019,"profit":0},{"algo":"Lyra2RE2","current_mining_coin":"vertcoin","host":"hub.miningpoolhub.com","all_host_list":"hub.miningpoolhub.com","port":12018,"algo_switch_port":17018,"multialgo_switch_port":12018,"profit":0.04185732},{"algo":"Skein","current_mining_coin":"myriadcoin-skein","host":"hub.miningpoolhub.com","all_host_list":"hub.miningpoolhub.com","port":12016,"algo_switch_port":17016,"multialgo_switch_port":12016,"profit":0.00562131},{"algo":"Qubit","current_mining_coin":"digibyte-qubit","host":"hub.miningpoolhub.com","all_host_list":"hub.miningpoolhub.com","port":12014,"algo_switch_port":17014,"multialgo_switch_port":12014,"profit":0.01064812},{"algo":"NeoScrypt","current_mining_coin":"feathercoin","host":"hub.miningpoolhub.com","all_host_list":"hub.miningpoolhub.com","port":12012,"algo_switch_port":17012,"multialgo_switch_port":12012,"profit":1.61472529},{"algo":"X11","current_mining_coin":"adzcoin","host":"hub.miningpoolhub.com","all_host_list":"hub.miningpoolhub.com","port":12007,"algo_switch_port":17007,"multialgo_switch_port":12007,"profit":0.00858894},{"algo":"Myriad-Groestl","current_mining_coin":"myriadcoin-groestl","host":"hub.miningpoolhub.com","all_host_list":"hub.miningpoolhub.com","port":12005,"algo_switch_port":17005,"multialgo_switch_port":12005,"profit":0.01061736},{"algo":"Groestl","current_mining_coin":"groestlcoin","host":"hub.miningpoolhub.com","all_host_list":"hub.miningpoolhub.com","port":12004,"algo_switch_port":17004,"multialgo_switch_port":12004,"profit":0.04799414},{"algo":"Keccak","current_mining_coin":"maxcoin","host":"hub.miningpoolhub.com","all_host_list":"hub.miningpoolhub.com","port":12003,"algo_switch_port":17003,"multialgo_switch_port":12003,"profit":0},{"algo":"Scrypt","current_mining_coin":"gamecredits","host":"hub.miningpoolhub.com","all_host_list":"hub.miningpoolhub.com","port":12001,"algo_switch_port":17001,"multialgo_switch_port":12001,"profit":0.02324832}]}

it's all in one minute of time so i don't understand why current coin is myraid.
can you inspect some coins you mine for that?

**Comment by aaronsace** [comment]
Sorry, are you querying an issue with MininingPoolHub stats or my use of them?

**Comment by aaronsace** [comment]
Wait those two coins are the same algorithm. It switches when a coin is found.

**Comment by lyolyalya** [comment]
i'm telling about miningpoolhub=)maybe his stats not so fast or something...cause with my understanding i must mine digibyte and MPH tells my miner to mine myraid.yes this is the same algo.i'm using v1.3 so far and waiting your final release with actual coin displayed and miners i suggested=)maybe that's the problem...cause with stats of MPH i mine with 0.007 BTC per day min, but a get 0.005 max...looks like that third of time i mine not max profitable coin...and single mining gives much better results now...
