### ISSUE TITLE
Auto Update

### ISSUE THREAD

**Issue by zaptrem** [MultiPoolMiner/MultiPoolMiner#393]
How difficult would it be to create a sub-script that would automatically run and check for new releases every day or so and automatically stop the script, download them, and run the script again? As this script gets minor updates frequently, it seems like a useful future feature.

**Comment by aaronsace** [comment]
Had thought about that. All the files can actually be updated without stopping mining except 'MultiPoolMiner.ps1'. Maybe if there was a separate script that ran the core program repeatedly instead of having a loop. It could also check and update the files and would prevent any memory issues.

**Comment by zaptrem** [comment]
Maybe the core (MPM.PS1) program could run a separate script every so often to stop itself and update MultiPoolMiner.ps1, and the core program could in turn periodically update the update script.

**Comment by fonyo** [comment]
@aaronsace Is this planned to be implemented for V3?

**Comment by aaronsace** [comment]
It was an idea; add it to the list.

**Comment by zaptrem** [comment]
Are the goals for v3 going to be implemented on the main branch? Or will there be a different branch. Will Fonyo be working on them as well?

**Comment by fonyo** [comment]
Yes, those are all planned enhancements for V3 master. I know a bunch of programming languages in and out but unfortunately, PS is not one of them, so I can only help with the project management, documentation, issues and testing side of things and tweaking the code where necessary. I noticed Aaron was lacking time to do these so I jumped in. You are all welcome to do the same and we actually do need a lot of feedback coming from testing if we want to have a successful V3 launch.

**Comment by lee-aaron** [comment]
Hello again,

Sorry for the hiatus! I've just started uni and trying to spend time in side projects whenever possible. Since I'm currently waiting for a friend to complete his portion of my current project, I decided to come back and help out. I've noticed some areas I can contribute to for V3 but am wondering if I can code this in python. Python can read PS scripts and execute them so I'm hoping that's fine? I've built a web scraper before so I can implement this auto updater within a week (due to classes etc).

**Comment by aaronsace** [comment]
@lee-aaron If you can tackle any features listed in version 3 then that would be great. I'll setup a dev branch soon to submit pull requests on. I would ask you stick to PowerShell and/or C#; if you have any programing experience then you will find them very simple languages.

**Comment by lee-aaron** [comment]
@aaronsace Yes, I am proficient in Java and am familiar with other languages (python, JavaScript, etc). I can try picking up PowerShell then. Looks similar to JavaScript.

**Comment by zaptrem** [comment]
@aaronsace Is this still planned?

**Comment by aaronsace** [comment]
@zaptrem I'm not tackling it at the moment and @lee-aaron is working on getting it to run on Linux.

**Comment by fonyo** [comment]
In the meantime a text file could be created in the root folder that only contains the version number of MPM. This would only be updated with a new release and the downloaded MPM can cross-reference this with the latest github master. If the version number on Github is different or larger, user could be prompted there is an updated version and maybe provided a link even. If there are significant core changes to come, auto-updating can be troublesome and cause issues with rigs maybe downtime even (due to need for a complete rebenchmark which isn't smooth for all users).

**Comment by lee-aaron** [comment]
My suggestion is for this is to make a String variable in MPM.ps1 and just
compare it to latest one on releases page. Then follow what fonyo suggested.

**Comment by zaptrem** [comment]
Does the script currently auto update miners?

**Comment by lee-aaron** [comment]
Don’t believe it does. We have to manually update the link on the repo.
