### ISSUE TITLE
Bug on start in MultiPoolMinerV2.7.0.2

### ISSUE THREAD

**Issue by Petyay** [MultiPoolMiner/MultiPoolMiner#536]
Hello.
Im using 2x 970Nvidia GPU, MultiPoolMinerV2.7.0.2. 
Аnd have this bug on start.
![multipoolminer v2 7 0 2 bug on start](https://user-images.githubusercontent.com/28813843/33241704-6a6317ca-d2da-11e7-86b0-114c3fa34f5a.png)

Please help.

**Comment by alucard20724** [comment]
you lined out your wallet in white, but you forgot to line out your wallet in the red.

**Comment by aaronsace** [comment]
Never seen this error before. 

A quick fix is to remover this line: 
`Add-Type -Path .\OpenCL\*.cs`

**Comment by platinum4** [comment]
This occurs when somebody has updated their drivers but has not rebooted and is trying to mine on the same Windows instantiation.  This is not an issue and the codebase has changed vastly between 2.7.0.2 and 2.7.1.4 so this can likely be closed.  You can replicate OpenCL errors by upgrading your version of Windows from 1703 to 1709 and Windows Update will move you to the Windows WHQL NVIDIA driver which is not the full package; this happens with AMD as well.  This issue is resolved with a proper driver installation and is rarely seen since mining is not generally tried without properly installed drivers.
