### ISSUE TITLE
Are you working towards adding support for ASIC machines?

### ISSUE THREAD

**Issue by tboy1337** [MultiPoolMiner/MultiPoolMiner#538]
Will MPM be able to control ASICs in the future for profit switching?

**Comment by aaronsace** [comment]
I'm not familiar if ASIC's but if there is a way to control it then it should be possible...

Is there some way of controlling an ASIC? How do they connect to a computer?

**Comment by tboy1337** [comment]
They have api's that you can use to control them, they are on local network normally.

**Comment by tboy1337** [comment]
Awesome Miner can do it but GUI is nightmare.

**Comment by tboy1337** [comment]
https://bitcointalk.org/index.php?topic=676942.0

**Comment by aaronsace** [comment]
So is it running Cgminer?

**Comment by tboy1337** [comment]
It depends, different machines use different miners, S9 (sha256) uses bmminer but the L3 (Scrypt) uses cgminer, you have to enable privileged API access though which requires logging into the machine through SSH or Awesome miner has a tool in the pro version to do it automatically.

**Comment by tboy1337** [comment]
Not sure what D3 (X11) uses.

**Comment by crazybrker** [comment]
I have an Antminer S7 and I think rather than switching miners and settings on the ASIC, the best idea would be to have the ASIC pointed to a Stratum proxy on your computer. If MPM were to help with this, it would need to provide a Stratum proxy that switches pools based on profitability. There are existing Stratum proxies but they seem outdated. https://github.com/Stratehm/stratum-proxy and https://github.com/slush0/stratum-mining-proxy and https://bitcointalk.org/index.php?topic=370365.0 

It might be excessive to combine this into the project...

**Comment by aaronsace** [comment]
I think using the API's would be best; you just need to edit the configuration file on the miner to allow API access. 

/config/bmminer.conf
```
"api-listen" : true,
"api-network" : true,
"api-groups" : "A:stats:pools:devs:summary:version",
"api-allow" : "W:0/0",
```
