### ISSUE TITLE
Request: Timestamp on Logs

### ISSUE THREAD

**Issue by Splitter9980** [MultiPoolMiner/MultiPoolMiner#554]
As per the title.

**Comment by crazybrker** [comment]
+1 for this. It would be good to simply add it to the display screen. There are times when MPM has frozen but the miners are still running, but I have no idea how long it's been frozen on that screen for.

**Comment by UselessGuru** [comment]
@crazybrker 

> how long it's been frozen on that screen for

Are you sure it is frozen (=hangs)?
MPM's powershell window stops scrolling once you click into it. This happened to me a lot and is caused by the default 'Quick Edit' option. The solution:
[https://serverfault.com/questions/204150/sometimes-powershell-stops-sending-output-until-i-press-enter-why](url)

**Comment by crazybrker** [comment]
The screen was "frozen", I'm not sure to what extent. I clicked inside of
the powershell window a couple times and pressed enter a couple more... It
could have been in quick edit mode, I'll pay more attention if it happens
again. Thanks for the advice.

On Dec 4, 2017 4:18 PM, "UselessGuru" <notifications@github.com> wrote:

@crazybrker <https://github.com/crazybrker>

how long it's been frozen on that screen for

Are you sure it is frozen (=hangs)?
MPM's powershell window stops scrolling once you click into it. This
happened to me a lot and is caused by the default 'Quick Edit' option. The
solution:
https://serverfault.com/questions/204150/sometimes-powershell-stops-sending-
output-until-i-press-enter-why <http://url>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/aaronsace/MultiPoolMiner/issues/554#issuecomment-348890185>,
or mute the thread

**Comment by theeddie** [comment]
Yes ill take anything, a blinking red dot anything on the main screen so i can glance and see if its working.

 the time running/current would be fine also , maybe hashrate also

**Comment by crazybrker** [comment]
Easy mod, I just put added this under line 508 in MultiPoolMiner.ps1
`Write-Host "Updated: $(date)" `
Then you can see the last time that it refreshed the screen.

**Comment by UselessGuru** [comment]
This has been implemented with https://github.com/MultiPoolMiner/MultiPoolMiner/pull/802
