### ISSUE TITLE
Lyra2z nvidia ccminer invalid device function

### ISSUE THREAD

**Issue by hybridtrendz** [MultiPoolMiner/MultiPoolMiner#584]
I'm running a 1070ti & 750ti through MultiPoolMiner. When mining Lyra2z, gpu #0 1070ti runs fine.  My second card, the 750ti gets error GPU #1 Invalid device function 

I assume the 750ti isn't actually doing anything even tho it says 196 mh/s

Any ideas?

Thanks

**Comment by fonyo** [comment]
Lyra2z cpu runs a gpu?

**Comment by tj1627** [comment]
I have the same issue running 1080 Ti, 1070 Ti, 980 Ti, 960 (I know, mostly a mashup of what I had on hand).  If you look at CC miner compatability wiki: https://github.com/tpruvot/ccminer/wiki/Compatibility it lists 6.1 (CUDA 8) for the 1080/1070/etc and 5.2 for the 980/960 etc.  Running Lyra2z through Multi Pool Miner runs fine on the 9xx cards (I suspect because the 960 is in PCI slot 0, so it defaults to settings matching that card) and shows this error on the 10xx cards.  

Is there any way to launch Multi Pool Miner for the 9xx cards and separately launch for the 10xx cards so they can be managed separately?  In the meantime, I removed Lyra2z from my algo list.

**Comment by UselessGuru** [comment]
@tj1627 
> Is there any way to launch Multi Pool Miner for the 9xx cards and separately launch for the 10xx cards so they can be managed separately? In the meantime, I removed Lyra2z from my algo list.

If you can figure out a working command line for this combo, then you could add the extra commands to the miner file.

Currently MPM cannot run separate miner instances for different card models (it does however run separate instances for AMD and NVIDIA).
 You can have a look in [this thread](https://github.com/aaronsace/MultiPoolMiner/issues/519) on how to implement separate threads per GPU model - highly experimental...

**Comment by luongk** [comment]
@tj1627 I've had the same issue with a 1080ti + 980 - it defaults to the CUDA 9 miner for me (presumably as the 1080ti is GPU 0) and comes up with an error for the 980, but interestingly it reports an erroneous hashrate for the 980 (>500MH/s) which screws with the benchmarking/auto profit switching.  I've removed it from my algo list for the time being.

**Comment by titvs** [comment]
Hi guys,
This miner has been updated to version 0.3.0. 

https://github.com/djm34/ccminer-msvc2015/releases

I have a system with a similar configuration (980 + 1050 Ti) and version 0.2.1 was giving me the invalid device function for the 980 chip.
Ive updated the miner on MPM to the latest version and its working ok now. The ccminer_cuda9.exe was dropped and theres only the ccminer.exe now. 
@aaronsace , MPM needs to be updated for this latest version i guess. :)

**Comment by UselessGuru** [comment]
I'l make a pull for the new miner version.

**Comment by UselessGuru** [comment]
> Is there any way to launch Multi Pool Miner for the 9xx cards and separately launch for the 10xx cards so they can be managed separately? In the meantime, I removed Lyra2z from my algo list.

You can set this on a per miner basis. You will need to edit the miner file \Miners\CcminerLyra2z.ps1:

Look for 
```
$Commands = [PSCustomObject]@{
    "lyra2h" = "" #Lyra2h
    "lyra2z" = "" #Lyra2z
}
```
and change both instances of '= ""' to = " -d 0,1,2" (note the leading space, numbers separated by commas) where the numbers must match all the device ID's the miner is allowed to use. Any other card will be ignored. The problem here is that you will having a card sitting dead while mining.

**Comment by UselessGuru** [comment]
Miner has been updated to version 0.3 which resolves this issue.
https://github.com/MultiPoolMiner/MultiPoolMiner/commit/1343594d6d21fbd75038844e44b5b9febf19e2e5
