### ISSUE TITLE
Algorythm Switching

### ISSUE THREAD

**Issue by dekkyy1111** [MultiPoolMiner/MultiPoolMiner#614]
Algorythm is stwitching every 5 to 10 minutes. Anything i can do to change that?
[2017-12-10_13-08-42.txt](https://github.com/aaronsace/MultiPoolMiner/files/1545619/2017-12-10_13-08-42.txt)

**Comment by UselessGuru** [comment]
@dekkyy1111 
> Anything i can do to change that?

Why do you want to change it? By switching MPM wil always mine the most profitable algorithm.
You can use the '-interval' (default  60 seconds) parameter to increase the time between algo switches.

**Comment by aaronsace** [comment]
@dekkyy1111 Half of that log is a benchmark; if you close and reopen then you should get a better picture. 

NVidia cards tend to switch every 10 minutes though because Ethereum is not profitable and there is no 'number 1' coin.

**Comment by Dim0N22** [comment]
Hello. 

I have the same issue with switching algorythms every 1-2 minutes. Log is attached.
Also, on AMD rigs you cannot set resolution higher than 640x480 when no monitor is attached. With such resolution it is impossible to read full logs.

It would be great if you could fix this.

[2017-12-10_19-25-07.txt](https://github.com/aaronsace/MultiPoolMiner/files/1545904/2017-12-10_19-25-07.txt)

**Comment by aaronsace** [comment]
@Dim0N22 Something is definitely wrong with yours, not just the log output. It is running fine then it literally just starts bouncing between two miners every interval. 

Is this the first time that this has happened? I think you have changed some of the files, do the original files have the same issue?

**Comment by Dim0N22** [comment]
@aaronsace Thank you for the reply.

I've restarted MPM with '-interval 1800' setting and it's doing fine: no bouncing at all. Log: 
[2017-12-10_21-11-48.txt](https://github.com/aaronsace/MultiPoolMiner/files/1546004/2017-12-10_21-11-48.txt)
Also, MPM worked fine for 12 hours yesterday and everything was perfectly OK with rare switches.

I guess BTC/Day was equal on both algorithms so it changed miners every minute. But I'm not sure because logs do not contain full info on profitability.

Also, I'm really changed some files: just deleted files for miners that I suppose are not efficient. I've left only Claymore miners.

**Comment by carlo0000** [comment]
so to fix this we have to increase the -interval?
because my miner too they switching after a 2-3 minutes and even worse when it just start the same one again  and when it start so much times i have some miner they crash they hang on create dag file for ether  and we lost so much mining time when it had to create so much often the dag

also notice the nvidia start the same miners more than 200 times on an half day

gonna increase the interval now

**Comment by aaronsace** [comment]
@carlo0000 Please can you post the logs as the switch every 60 seconds is a bug?

**Comment by carlo0000** [comment]
ok i take the log of nivida ring
[2017-12-09_15-30-32.txt](https://github.com/aaronsace/MultiPoolMiner/files/1548062/2017-12-09_15-30-32.txt)

an amd log  i had to cut, the log was 60mb
[2017-12-09_02-33-09.txt](https://github.com/aaronsace/MultiPoolMiner/files/1548043/2017-12-09_02-33-09.txt)

**Comment by fonyo** [comment]
@aaronsace I have the same issue with DSTM, it doesn't work, fails 70 times in a short period of time but it will not get removed as others.

**Comment by carlo0000** [comment]
i have the interval on 300  working fine sins then
execpt on my gtx1080i ring ccminer crash a lot than it idle for couple of minute 
i think intensity is to high on keccak algo  i sow 50% reject share on my 1080ring 
can we decrease the intensity somewhere?

i also notice  sins i put 300 on interval, the memory bug is gone (before i had to restart multipool each day because it used all the computer memory after a day)  but now it s stay under 500mb
