### ISSUE TITLE
Intensity and CPU threads

### ISSUE THREAD

**Issue by JohnDelisle** [MultiPoolMiner/MultiPoolMiner#654]
It'd be great to have a way to configure mining intensity (ie ccminer --intensity setting) and CPU threads (ie cpuminer --threads).  

I see I can do this by editing each miner's ps1 script, and adding the parameters to each algo, but that's a lot of editing for something I'm trying to apply at a global level.

Use-case for this would be people like me, who need some CPU cores free for using the computer, and some GPU power for simple tasks like surfing and minecraft.

Thanks

**Comment by komer83** [comment]
I had to manually edit every single CPU file for my 8700. But hi, it worked great.

**Comment by aaronsace** [comment]
There are a lot of miners so, for there to be a setting in MultiPoolMiner, they would all need to be normalized. No my to-do.

**Comment by mahpoul22** [comment]
Hey @komer83, how did you do it?

**Comment by GoodbyeWorld** [comment]
@mahpoul22  I did it by opening each of the PS1 files in the Miners directory, and appending my desired intensity or CPU threads to the command line.  It's quick and dirty.. not the right way.. but I needed something fast.

**Comment by GoodbyeWorld** [comment]
@aaronsace Not sure normalizing it makes sense.  What would you normalize against?  

For example, with "--intensity=19" on all ccminer variants, I'll see the same level of GPU load, but differing performance in hash/sec (because some binaries out-perform others, as expected).  From a usability standpoint, using "--intensity=19" is the right choice, since my system performs consistently well at that level.  

Same applies across other miners, like the cpuminer and its variants.  "--threads=6" is good for me, and my CPU use is consistent regardless of the binary running, and regardless of its hash/sec efficiency at 6 threads.

If anything, I'd suggest making this easy to adjust at a per family of binaries level.  All the ccminer variants are one family, where I'd like to specify "--intensity=19" for all of them in one easy place.  Same for all cpuminer variants, where I'd specify "--threads=6".  Etc etc for other similar binaries.

I don't think you have much normalizing or base-lining to do - might be easier to leave it to the user, since they're almost certainly adjusting this to make the system functional for day-to-day use, with hash-rate being secondary to system stability and usability.

**Comment by newt0this** [comment]
@GoodbyeWorld  Could you please be more specific about how you changed the PS1 files? I am a noob with this stuff, and I don't want to run my hardware into the ground.

**Comment by newt0this** [comment]
Another take on this would be allowing the user to set maximum temperatures for the cpu and gpu.

**Comment by UselessGuru** [comment]
@newt0this 

> Could you please be more specific about how you changed the PS1 files? I am a noob 

Open the miner file, e.g. .\miner\CcminerPalgin.ps1 and look in the '$Commands = [PSCustomObject]@{' block for the algo you want to change intensity, e.g. blake2s:

$Commands = [PSCustomObject]@{
    #"bitcore" = "" #Bitcore
    "blake2s" = " -put your command here" #Blake2s
...

To increase intensity you might put " --intensity=19" (note the leading space character). The numbers depend on card model, algorithm and miner. There is not 'correct' value here. You will have to spend a lot of time to find the best parameters for each card, algorithm and miner.

To find out what parameters are available run the miner executable with the ' --help' option.

If you want to disable an algo for a specific miner, then insert a '#' character directly before the "algo" = "", as seen in above example with #"bitcore".

**Comment by UselessGuru** [comment]
@aaronsace 

> There are a lot of miners so, for there to be a setting in MultiPoolMiner, they would all need to be normalized. On my to-do.

I think we should build a database with the best performing parameters for each card model / algo / miner combination. This information could then be applied by MPM.

More often than not are the defaults used by the miner developer suboptimal, and one can achieve higher rates (approx. 1-4%) by fiddling around with intensities.

**Comment by thericeking** [comment]
@aaronsace Thanks for bringing this up. It's disappointing to learn that my GPU's are been push to the maximum. No wonder my GPU temperatures are lower and fans quiet. I don't like this. Can you write a wiki on how to on Redddit and post the link here?

**Comment by jake5253** [comment]
For anyone that wants to change the CPU threads, its as easy as adding "-t <number of threads" to each of the ./Miners/cpuminer*.ps1 files under the Arguments towards the bottom.  For simplicity I just added it at the beginning
`Arguments = "**-t 7** -a $_ -o $($Pools.(Get-Algorithm $_).Protocol): .... `
I pawed through the include file and some other areas, I'm just not sure what changes to make or where, in order to add it more easily.  Fortunately, there's only about ten files you need to change at most. My computer tends to use cpuminerjayddeeavx2 primarily.

**Comment by UselessGuru** [comment]
@jake5253 

Adding it to command line is perfect. You do not need to change anything anywhere else.
If you want to use different thread numbers per algorithm then set the parameter in the 
```
[PSCustomCommand]@{
...
    "x17" = " -t 7" #X17
...
}
```
Note the leading space as first character - it is essential! :-)
