### ISSUE TITLE
processing scheduler has several errors

### ISSUE THREAD

**Issue by nemosminer** [MultiPoolMiner/MultiPoolMiner#694]
https://github.com/nemosminer/NemosMiner-v2.2.2/issues/74

**Comment by aaronsace** [comment]
Are they using Task-Scheduler to start the script?

**Comment by aaronsace** [comment]
Probable good to have the second check to force close instead. Not quite sure I follow why CloseMainWindow is not working for him though...?

**Comment by grantemsley** [comment]
Sometimes CloseMainWindow doesn't work.  It asks the miner nicely to close, but doesn't force it to.  I noticed that you can get multiple copies of a miner running accidentally when some fail to close.  Mostly ccminer, but other's have done it too on my systems.

In my own fork, I changed it to something like this which I think is a little more elegant:

`
$Miner.Process.CloseMainWindow() | Out-Null
# Wait up to 10 seconds for the miner to close gracefully
$closed = $Miner.Process.WaitForExit(10000)
if(!$closed -and -not $Miner.Process.HasExited) {
    Write-Warning "$($Miner.Name) did not close gracefully.  Killing process."
    $Miner.Process.Kill()
}
`

This tries to close the miner properly, giving it a chance to do any cleanup work it needs to do before closing, then waits up to 10 seconds for it to finish.  If it hasn't exited on it's own after 10 seconds, it gets forced to exit.

This is better than just sleeping for a set amount and blindly killing them, because it won't have to wait if the miner closes on it's own quickly, but will let it do any clean up work it needs to do.

**Comment by aaronsace** [comment]
@grantemsley Awesome idea.
