### ISSUE TITLE
Did not switch back from donate. Mined 16 hours and 38 minutes before i noticed

### ISSUE THREAD

**Issue by simbee** [MultiPoolMiner/MultiPoolMiner#807]
Noticed that one of my workers didnt show up on mininpoolhubstats. Everything seemed fine in the MPM window, it had been doing lyra2z with ccminer to aaronsace.multipoolminer for 4 minutes. Then I hit a key on the keyboard and the window updated. The 4 minutes was actually 16 hours. 

I like your software and im happy to use it, so no big deal. But im curious to what happend. The logfile is blank between 4 min and 16 hours. Any ideas?

**Comment by thericeking** [comment]
Yikes!!!

**Comment by grantemsley** [comment]
What happened is you selected something (dragged the mouse over the text).  This completely freezes the script - which is intentional, windows thinks you are trying to select some text to copy and it would be irritating if the screen kept scrolling while you did that.

You can open a command prompt window, click the icon at the top left, click properties, and uncheck "QuickEdit Mode".  This disables the ability to highlight to copy/paste.

Unfortunately it's a system wide setting and there is no way to disable it for just one window.  So you can either disable it for the entire system (which also irritatingly disables using the scroll wheel to scroll in the window), or just be careful not to select text.

**Comment by fonyo** [comment]
You can always confirm/check whether anything is selected if you look at the the title of the window. Test and see for yourself how it changes to avoid this in the future.

**Comment by paulpoco** [comment]
I find if you happen to click inside the window, I just hit Enter and all seems good.

This is really good for the odd time the screen is blank, I hit Enter and all the text coming rolling back on the screen.
