### ISSUE TITLE
I keep getting Failed to connect to miner... 

### ISSUE THREAD

**Issue by Pititul** [MultiPoolMiner/MultiPoolMiner#813]
After Failed to connect to miner with Tpruvot and KlausT... then the algo goes away... 

Is the interval below says how long it sleeps? I tried to change it to 1. 

$Delta = 0.05
$Interval = 5
$HashRates = @()

**Comment by Pititul** [comment]
WARNING: Stat file (CcminerAlexis78_X17_HashRate) was not updated because the value (37217630) is outside fault tolerance.

Appears 3 times and also disabled.

**Comment by cmbconcretefire** [comment]
Same here.

**Comment by fonyo** [comment]
You can remove -watchdog from your start.bat for now for a temporary fix.

**Comment by Pititul** [comment]
Would it still disable not working minets like it used to? I understand that Watchdog temporary disable the miner. But MPM used to have permanently disable miners too and only deleting hashrate file in stats to get it back.

**Comment by UselessGuru** [comment]
@Pititul 

> Is the interval below says how long it sleeps? I tried to change it to 1.

It defines how log MPM sleeps between reading hashrates. Do not change this - you are likely to get unreliable hashrates.
There is also a variable $interval in the main program. This value is settable in start.bat and defines how long MPM waits before it reads hashrates

https://github.com/MultiPoolMiner/MultiPoolMiner/issues/821

>  But MPM used to have permanently disable miners too and only deleting hashrate file in stats to get it back.

All watchdog data is in-memory only and will get lost on MPM exit. Watchdog does not delete/rename any files (e.g. poolfiles or benchmark files)
Deleting the hashrate file will always cause re-benchmark.

**Comment by UselessGuru** [comment]
@Pititul 

Are you running multiple copies of MPM on the same PC?
If I understand you correctly you are getting 0 hashrates. These are cause if the port is already in use (or is blocked) and the API file cannot read the hashrate from the miner.

What do you get if in a PowerShell window you run the following command while running a miner:

Get-NetTCPConnection -State "Listen" -LocalPort **PutYourMinerPortHere**
e.g. Get-NetTCPConnection -State "Listen" -LocalPort 4068

You should see something like
```
Get-NetTCPConnection -State "Listen" -LocalPort 4068

LocalAddress                        LocalPort RemoteAddress                       RemotePort State       AppliedSetting OwningProcess 
------------                        --------- -------------                       ---------- -----       -------------- ------------- 
127.0.0.1                           4068      0.0.0.0                             0          Listen                     5448          
```
If not, then MPM cannot access the miner API cause the port is blocked.
The OwningProcess number is the process ID (PID)of the application listening on port 4070. 
Check in task manager if this number matches the process is of the miner executable:
![untitled](https://user-images.githubusercontent.com/30080938/34396642-e8cfc0e4-eb6d-11e7-8631-dfd3b464c7da.png)

What happens when you run this in a powershell window:
```
        # $Client = New-Object System.Net.Sockets.TcpClient 127.0.0.1, 4070
        $Client = New-Object System.Net.Sockets.TcpClient 127.0.0.1, **PutYourMinerPortHere**
        $Stream = $Client.GetStream()
        $Writer = New-Object System.IO.StreamWriter $Stream
        $Reader = New-Object System.IO.StreamReader $Stream
        $client.SendTimeout = 5
        $client.ReceiveTimeout = 5
        $Writer.AutoFlush = $true

        $Writer.WriteLine("Summary")
        $Reader.ReadLine()
```

**Comment by Pititul** [comment]
Nope, just one copy. I took watchdog out and it is mining normally, with hashrate showing at the pool website. The shares are accepted also.

I'll check the port as you suggested.
