### ISSUE TITLE
Miner hashrate vs pool hashrate

### ISSUE THREAD

**Issue by tarioch** [MultiPoolMiner/MultiPoolMiner#841]
Is there any interest in having code to fetch the hashrate reported by the pool? Or is the hashrate by the miners normally good enough to make the decision?

I've code around for fetching hashrate for yiimp based pools as well as mph.

Once #801 is done I plan to do some monitoring to compare the two rates.

**Comment by grantemsley** [comment]
I'd love to be able to track it, even though I'd still have it make decisions based on the miner's report.  It would be nice to see if there is a big difference that might indicate a problem with the pool.

I'd also love to be able to track the expected vs. actual profit for each pool (which would have to be tracked across all workers, since the balances are separated by address not worker) to verify that the profitability information they give is at least somewhat accurate.  

It probably wouldn't be useful for minute to minute switching decisions, but it would help long term decide if there are any miners or pools you should drop because they aren't actually paying out what is expected.

**Comment by fonyo** [comment]
I was thinking the same, moreover reported/recorded hashrate could be adjusted with a simple math percentage if some of the miners are problematic and we could determine roughly by how much worse they are than they telling us so.

@grantemsley The miner sw could also be the culprit as we see it with the LyraZ and Lyra2ReV2 miners.
BTW, I do need to (want to) test your monitoring thing :) ! Please drop me a message on Skype @ fonyo_tnf when you have time to give me a quick tour of what you have done. I have got plenty of time tomorrow if you are free for a quick conversation. 

Also, there is http://miningpoolhubstats.com
You, gents, should have a look at it.

**Comment by fonyo** [comment]
@tarioch Responding to your original query. It is currently impossible and not feasible due to pool limitations. But we have ideas and are working on it with the pools.

**Comment by tarioch** [comment]
@fonyo what limitations are you talking about? I'm able to fetch the information for both mph and yiimp clones (although for the yiimp clones I had to parse some html to get it).

Current code I'm using (still under heavy development is here: https://github.com/tarioch/poolmon)

Basically I'm fetching the data and putting it into an influxdb where I then run grafana for generating charts/reports.

**Comment by grantemsley** [comment]
@tarioch I'm guessing the pool operators would not like you scraping their pages.  Most of them have a hard enough time keeping the website portion operational. I have seen them turn off the worker stats or even entire website when under heavy load.

Not a big deal if a few people are doing it, but potentially a big problem if it becomes widespread.

**Comment by tarioch** [comment]
True, on the other hand I'm only parsing a part that usually gets requested by xhr request (so gets refreshed automatically all the time when the page is open). But would definitely be nicer if that would be exposed properly on the api (like it's done on mph)

**Comment by grantemsley** [comment]
@fonyo send you a skype message (I think I got the write person...haven't used skype in ages).

**Comment by fonyo** [comment]
@tarioch 

What @grantemsley said is one of the reasons. The other reason is, these are inaccurate and not updated in real-time.

**Comment by tarioch** [comment]
After running it >24h here's a first outcome, median rates for a 1080TI system using zpool vs rates from mpm/miner:

lyra2v2: 35MH/s vs 68MH/s
neoscrypt: 1MH/s vs 1.38MH/s
sib: 6MH/s vs 20MH/s
skunk: 45MH/s vs 52MH/s

**Comment by bbgobie** [comment]
Which miner are you using for lyra2v2? The Dsjm one is the one for me that reports closest on MPH.
Others like Tpruvot report way higher than the pool does even with --stale-shares option.

**Comment by tarioch** [comment]
Excavator is used for lyra2v2

I have the monitoring now hooked up with the new monitoring pushes from mpm, so after running this for a day or two should be able to get some even better stats out of it :)

**Comment by UselessGuru** [comment]
I had a closer look at skein. I tested several pools (zpool, mph) and miners (Ccminer-alexis, KlausT817 & CcminerHSR, Ccminer 2.2.3 & CcminerSP).

All of them reported approx 60% higher hashrate than at the pool. Can anyone confirm this finding?

I am not using skein at all because MPM will calculate incorrect profitability.

**Comment by fonyo** [comment]
I am not trying to imply anything but there are some pools that cheat with hashrates. Just please bear that in mind.
