### ISSUE TITLE
A few simple questions. 

### ISSUE THREAD

**Issue by cmbconcretefire** [MultiPoolMiner/MultiPoolMiner#848]
I keep my eye on the 'master' list to see if any changes have been made recently. (There have been) "Recently = past several hours or past 2 or 3 days." 

1) When changes are made / or added to the master file, do those changes get added to .zip file that is available on the main 'releases' page? OR, are they just experimental changes that do not get added to the main release .zip file? 

2) I know, I know, I know everybody says don't mine the X - algos, but I'm sorry, X17 is the most profitable algo that is in my bat file. And it's more profitable by A LOT. Like 2 x the others. Here's the problem > The Palgin mod is the fastest miner for x17, but for some reason it fails and MPM eventually reverts to the Tpruvot miner and it doesn't fail but is slower. Any explanation for this? 

3) After a while of mining with MPM, the number of days and time mined gets really messed up. It will say a miner has been mining for thousands of days.

**Comment by grantemsley** [comment]
1. Some get added, some get reverted.  Master is the work in progress.  The zip files are released when they are ready to.

2.  The newest Palgin miner that was updated yesterday requires very new drivers.  Upgrade your Nvidia drivers to 388.71

3.  Dunno what you're talking about there.

**Comment by cmbconcretefire** [comment]
@grantemsley 
1) I understand what you're saying. What I am not clear on is this: > Let's say a file (any of them) was updated 2 or 3 hours ago in the master branch. Does the zip file on the release page get "updated" with that file change? (Even if no mention of it is made on the release page?) 

2) Thanks for the tip about updating drivers. I did. 
3) Under 'Status: Running' - it shows NVIDIA-Palgin\ccminer.exe has been running for 152,302 days, 3 hours and 38 minutes. 

4) You mentioned "the newest Palgin miner that was updated yesterday" ---- Ok, simple question regarding that miner. Does MPM automatically download and "update" that / those miners in real time......OR....is that our responsibility to keep up with updated miners and download them ourselves? 
Thanks!!!

**Comment by grantemsley** [comment]
1. No, releases get made manually when it's ready.  What's in master is the bleeding edge potentially broken code.  Sometimes it works and has great new features.  Sometimes it's not working at all.  And sometimes it looks like it works but is broken and not doing what it should.  If you aren't a programmer, you could probably stick to the release version once things are working well and they make a new release.  If you run master, expect issues, and don't expect them to be fixed right away.

3.  Never seen that before.  But my systems switch often enough that they wouldn't run that long anyways.

4.  It tries to update them automatically if the files don't exist.  Sometimes that fails and you have to download them manually.  It does NOT update miners where the files exist, but a new version is available, which is why you are supposed to not copy them over from previous releases.  If you are using master, you'll have to keep track of which are updated and delete the files to the script knows to download them again.  Also, if you have issues with it not downloading them, you may need to disable your antivirus AND windows defender.

**Comment by cmbconcretefire** [comment]
@grantemsley , thank you very much for the info. I am going to stay away from the master now that I understand. If you could clear up the last one, number 3, I'll close this. You said - 'It tries to update them (the miners) automatically IF the files don't exist. Sometimes that fails. It does NOT update miners where the files exist, but a new version is available......" < What I read from that is that even though I HAVE > Bin\NVIDIA-Palgin\ccminer.exe from (say) a week ago.......MPM will NOT update to the version that was released yesterday. Do I have that correct? @grantemsley

**Comment by grantemsley** [comment]
Correct.  If the file exists, the script doesn't check the version.  If the file doesn't exist, it will download the latest version.

But the exact versions of miners to download are coded into the script.  So even if there was a new ccminer.exe released today, it wouldn't download that version until a new release comes out specifying the new version.  Which is good, because sometimes newer versions break things.

**Comment by cmbconcretefire** [comment]
Gotcha. I'm going to open a new topic in just a sec if you want to chime in. Thanks again.
