### ISSUE TITLE
MPM "learns" @fonyo 

### ISSUE THREAD

**Issue by cmbconcretefire** [MultiPoolMiner/MultiPoolMiner#849]
Let me say, I am NOT trying to be combative. I'm just trying to understand because what has been said doesn't LOGICALLY add up. 

Fonyo has said that MPM "learns" over time and will ignore certain algos for various reasons. This is cool. 
Fonyo has also said that he / nor anyone / can predict which algo's will be profitable one day, and not the next. Meaning ANY algo can shoot up in profitability at any given time.  < I agree with all of this. 

But then comes the part that seems to negate those words. 

It has been said time and again that it is not wise to include every algo under the sun in the .bat file. HOWEVER, if I am only mining at zpool, and no other pool.......wouldn't it be wise to include every algo that they provide / let them all benchmark / and THEN let MPM "learn" (over time) which ones to ignore? > Given that any algo can rise in price at any time, it doesn't make sense to me to automatically remove them ON MY OWN from the .bat file. (again, only mining at Zpool) 

What am I missing here? 

And a follow up ?. Does MPM have the ability to "re-learn" , and start accepting algo's that it has previously "learned" to "ignore?"

**Comment by platinum4** [comment]
Yeah, they fluctuate, I've added more algos and been rewarded like on nist5

**Comment by fonyo** [comment]
I am trying to be selective with the words, hence the word "learn". It is indeed very basic learning as it accumulates data over time (not just the hashrates of your cards) and the logic allows this to be used and act accordingly.

I meant *all algorithms that MPM supports* which is a larger set than what zpool has. Will clarify that if I put it in the README that way. It is still recommended to keep the included algos to the most profitable ones.

MPM gathers data of all coins available to it from all pools even if you don't mine them. It creates averages for these. Once it has all of these averages after around a week, it can accurately ignore spikes but also more accurately select the most profitable algos. If an unprofitable coin is steadily rising then that is a different case. The average will change over time and it becomes more profitable.

There are other variables and logic such as the watchdog and switching prevention.

I hope you understand we cannot feasibly include 20 paragraphs of explanation in every post, MPM's logic is becoming very complicated (which is a good thing, it now accounts for a lot of things) and I have been working hard to include that and expand the README (it is still incomplete, hopefully today I can finish adding all the new commands). MPM has got a lot of new features and significant changes since 2.6! 

I hope the above sufficiently answers all of your questions.

**Comment by cmbconcretefire** [comment]
@fonyo , yes I understand that lengthy answers are not feasible. I will try to do better in asking my questions from now on. Let me try to re-ask my question and get to the HEART of my ?. 

"it can accurately ignore spikes but also more accurately select the most profitable algos. If an unprofitable coin is steadily rising then that is a different case. The average will change over time and it becomes more profitable."

The HEART of my question is : If MPM's learning curve dictates that it ignores (abc algo) , and if MPM is left running for a month, and during that month (abc algo) actually does become relevant and profitable, Will MPM correct itself and NOT IGNORE that algo? 

Thanks for your contributions.

**Comment by UselessGuru** [comment]
@cmbconcretefire 
> wouldn't it be wise to include every algo that they provide / let them all benchmark / and THEN let MPM "learn" (over time) which ones to ignore?

No, it would not. The more algos you include the more like MPM will switch miners. Each time you swith a miner you will actually loose shares and profitablilty will go down.
Nicehash is the exception to the rule due to its payment scheme.

This makes good reading on the subject:
[http://give-me-coins.com/support/faq/what-is-pplns/](http://give-me-coins.com/support/faq/what-is-pplns/)

**Comment by fonyo** [comment]
@cmbconcretefire Okay, I will rephrase that answer:

##### Yes
