### ISSUE TITLE
Suggestion: poolsBackUp

### ISSUE THREAD

**Issue by ThomasSRL** [MultiPoolMiner/MultiPoolMiner#852]
Hi,
Perhaps have backup pools as an option? This way I could use MPH as main pool, but when watchdog notices fails it goes to ZPool?

Unsure if this is possible or even feasable?

**Comment by grantemsley** [comment]
If you only enable algorithms that MPH supports (and there is a list for each pool at https://multipoolminer.io/algorithms), and only specify MPH in your pools setting, it will always mine at MPH unless MPH is down.  When MPH is down, it will try mining at any other available pools.

If you put the pools you really don't want to mine at in -ExcludePools, it will only use those as a very last resort.

So you want something like:

```-Pools MiningPoolHub,MiningPoolHubCoins -ExcludePools AHashPool,Hashrefinery```

Along with the appropriate algorithms specified, that will mine at MPH most of the time, resort to zpool if MPH is down, and finally if both MPH and zpool are down it will try AHashPool and Hashrefinery.

**Comment by robl45** [comment]
I was going to ask this too, so basically we can have an exclude pool that will work as a pool of last resort if we go to sleep and the main pool goes down.  Why isn't this in the read me or anything?

**Comment by grantemsley** [comment]
@robl45 because it was just added days ago, and @fonyo has been working furiously to update the documentation.  It's documented at https://multipoolminer.io/docs, but it probably could stand to be a little clearer how PoolName and ExcludePoolName interact with each other.

**Comment by fonyo** [comment]
@grantemsley you forgot about nicehash. :)

What I was just wondering and came here to post about how the order of failover works. Has anyone tested this?

Test case:
1. So let's exclude MPH by not including username in the start.bat.
2. So my main pool will be zpool only as -poolname zpool.

If zpool goes down which pool will be picked next? What determines the order?

**Comment by fonyo** [comment]
Regarding being clearer, yes, I will try to provide examples and more sample usage but there is only so much we can include to not clutter the README (and only so much time I have in general). For me, it is obvious how these new commands can be utilised. I know this is not the case for everyone, but yet again, I am worried the Documentation will be unnecessarily enormous.

Docs can be edited, please feel free to do a pull request. I will add more info on these to the README as soon as I am able to.

**Comment by fonyo** [comment]
@robl45 if you add anything to one of the exclude commands, those will be treated like you deleted pool files, algorithms, miner files. They will NEVER be used, and will be excluded from failover, too.

**Comment by grantemsley** [comment]
@fonyo I didn't forget.  I'm just not very happy with them right now 😡 

I haven't actually tested it, but my understanding from reading the code is:

Algorithm is most important.  So if only one pool supports the most profitable algorithm, that pool will be used regardless of any pool settings.  So lets assume the most profitable algorithm is one they all support.

Lets assume you are using ```-poolname zpool``` and ```-excludepoolname nicehash```

- Zpool will be used if it is available, because it's in poolname
- If Zpool is down, any of the other pools (except nicehash) will be used - the most profitable one will be picked
- If all of those are down, it will resort to nicehash
- If nicehash is also down, it'll sit there saying there are no pools until something comes back up.

I believe you are incorrect that adding it to the exclude command treats it like you deleted the pool file.  That's true for algorithms and miners, but not pools - for pools it merely sorts them to the bottom of the list.  Well, almost true - the miners and algorithms still get loaded, so there is a bit of a performance hit for keeping the files and just excluding them.

**Comment by robl45** [comment]
I'm not exactly sure why we need exclude switches as you can just delete the miners or algorithms although I suppose it does make things a bit easier.

As for the excludepoolname, if it works as Grant is saying, that is not too bad.  IMHO it would be better if we could specify a pool and it just used that pool regardless of which algorithm was set.  Then maybe a failover switch to have another pool as backup if that pool failed.

**Comment by fonyo** [comment]
@grantemsley Yep, you are right. Just tested it. 'Algorithm' is still higher in execution hierarchy than 'ExcludePoolName', but 'ExcludeMinerName' is now higher than 'algorithm'.

**Comment by fonyo** [comment]
@grantemsley so do you an idea of the order of failover?

**Comment by grantemsley** [comment]
It'll pick the post profitable of the pools in Poolname first.  Then the most profitable that isn't in either list.  Then the most profitable from excludepoolname.

So you can basically have 3 levels of preference if you really want.

I prefer looking at it as either or - specify the pools you prefer, or specify the pools you hate.

**Comment by fonyo** [comment]
Sorry, I meant the order of the pools that are not in a list.

**Comment by grantemsley** [comment]
They get sorted by profitability, and only used if none in poolname are available.

**Comment by fonyo** [comment]
Awesome, thanks! You saved me a lot of time testing this.
