### ISSUE TITLE
Odd benchmark results

### ISSUE THREAD

**Issue by qck4fun** [MultiPoolMiner/MultiPoolMiner#854]
Hey guys,
could you please explain me these results of benchmarking...
   
Type: NVIDIA
Miner           Algorithm         Speed BTC/Day Accuracy BTC/GH/Day Pool
-----           ---------         ----- ------- -------- ---------- ----
CcminerLyra2z   Lyra2z      855.42 MH/s 0.16258     99 %    0.19006 MiningPoolHub-Zcoin
CcminerTpruvot  Lyra2z      384.77 MH/s 0.07313     99 %    0.19006 MiningPoolHub-Zcoin
CcminerNanashi  Lyra2z      350.37 MH/s 0.06659     99 %    0.19006 MiningPoolHub-Zcoin
FireiceNvidia   CryptoNight 170.00  H/s 0.00003     95 %  191.68461 MiningPoolHub-Monero
ReorderNvidia   Skein        33.86 MH/s 0.00002     63 %    0.00056 MiningPoolHub-DigibyteSkein
CcminerLyra2RE2 Lyra2RE2      2.67 MH/s 0.00001     91 %    0.00560 MiningPoolHub-Monacoin

I guess there's something wrong, because I'm running only one GPU and it's very old one... GeForce GTX 560 Ti.
It's not the first time it returned these results. I've tried to run the benchmark multiple times

Could you please tell me why I get these results?

**Comment by grantemsley** [comment]
Take a look at the actual miner windows - I bet they are throwing all kinds of errors.  You'll need to figure out which ones don't work on your hardware and disable them.

Unfortunately, some of the miners aren't very well behaved, and when they are getting errors because of unsupported hardware, instead of just exiting they report really high hashrates.

**Comment by qck4fun** [comment]
Ok then, the second paragraph explains it all.
Thanks for your help!
