### ISSUE TITLE
Why is this mining skein?

### ISSUE THREAD

**Issue by robl45** [MultiPoolMiner/MultiPoolMiner#868]
Makes no sense to me.  Skein has accuracy of 20%.  I'm assuming its BTC rate times accuracy or something like that so PHI should be mining right now.

![image](https://user-images.githubusercontent.com/34346751/34451483-35362b0c-ecf5-11e7-82e0-ccd5626f95b4.png)

**Comment by UselessGuru** [comment]
I had a closer look at skein. I tested several pools (zpool, mph) and miners (Ccminer-alexis, KlausT817 & CcminerHSR, Ccminer 2.2.3 & CcminerSP).

All of them reported approx 60% higher hashrate than at the pool. Can you confirm this finding?

I am not using skein at all because MPM will calculate incorrect profitabilit.

**Comment by thericeking** [comment]
@UselessGuru Hu? How is that MPM fault? That's what Multi Pool Hub is reporting to be the most profitable some days so that's what it mines. I check the site for most profitable every time it mines Skein and it looks accurate to me. Just because is just a rare coin it doesn't mean is not profitable. After all MPH takes care of exchanging so I can care less what I mine as long as MPM mine what MPH says is most profitable to THEM for exchange. I don't understand the problem.

**Comment by UselessGuru** [comment]
> How is that MPM fault?
MPM will calculate incorrect profitability.

It seems that my original wording is misleeding:
The calculated profitability will be far higher that what you will really get:
MPM reads the reported hashrate via API call directly from the miner, e.g 139MH as per your screen shot.
MPM then multiplies this value with the pricing information received from the pool -> expected profit.

However when you look at the pool, the pool will only report approx 60% of the hashrate of what the miner reports
-> 2 possibilities:
a) someone is stealing hashes (the pool)
b) someone is faking hashrate (too high, the miner)

I not blaming either one, it is just a fact that is true for many pools/miner combinations. 👎
