### ISSUE TITLE
Mining with Nvidia GRID K1 - Compute Compatibly 3.0

### ISSUE THREAD

**Issue by speedyrazor** [MultiPoolMiner/MultiPoolMiner#871]
Hi, I have a Nvidia GRID K1 Compute Compatibly 3.0 card and I have compiled ccminer with Compute Compatibly 3.0.
I have previously been using MultiPoolMiner with a 1080Ti and CPU, so now need to use this Compute Compatibly 3.0 compiled ccminer and the Grid K1 card. I tried a few manual commands with different coins and algos but get various 'unsupported' errors, including "Sorry neoscrypt is not supported on SM 3.0 devices", "Sorry, This algo is not supported by this GPU arch (SM 3.0 required)", "Invalid Device Symbol".
I tried using MultiPoolMiner, but after a while it crashes the OS and needs reboot.
I would love to use this card with MultiPoolMiner, is there anyway to do this with my compiled ccminer please?

**Comment by UselessGuru** [comment]
MPM works with any miner software that is controllable via command line. 
The errors & crashes you are encountering are not causes by MPM. 
They are caused by the miner (incorrect parameters / usage etc). 

Two things need being done:
1. Fix the miner software so it does not crash
2. Create a miner file with the proper commands for your miner
