### ISSUE TITLE
donation set at 10 min went for 1 hour

### ISSUE THREAD

**Issue by RANGERBEE** [MultiPoolMiner/MultiPoolMiner#966]
I let it run and waited to see if it would switch over and it did not. I restarted the miner after 60 minutes and it started with my profile then after. I believe there is a bug in the "check" on the timer?

At this time I am paid forward for 60 days. Hope you have it resolved by then..  I dont mind giving 10 min of every 24 hours.

**Comment by aaronsace** [comment]
Full logs please.

**Comment by RANGERBEE** [comment]
log attached.
[2018-01-06_17-12-31.txt.log](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1609490/2018-01-06_17-12-31.txt.log)

**Comment by aaronsace** [comment]
Both miners fail to close; it's a general switching failure rather than a donation bug. 

If you check the log, aaronsace counts to 10 minutes but somename is also still increase in time. At the 10 minute mark, MultiPoolMiner actually switches back and but both times become no longer valid and continue counting.

**Comment by aaronsace** [comment]
Changes are being made in the launching/closing area; whether it fixes that issue, I'm not sure.

**Comment by RANGERBEE** [comment]
thanks!
