### ISSUE TITLE
What does -switchingprevention 2 do?

### ISSUE THREAD

**Issue by Lycerion** [MultiPoolMiner/MultiPoolMiner#968]
What are the available options for this?

**Comment by UselessGuru** [comment]
@fonyo Can you include this in the readme?

Some coins/ algos fluctuate in price a lot. It is not advisable to just always jump to the highest paying coin/algo.

This number (0 - 10) is a factor used in MPM's internal calculations to determine which algo to mine next.
0 = Always mine the coin/algo the pays best at this very moment (this will lead to pool/algo hopping, therefor loosing profit!)
1 - 10: The higher the number the more MPM will honor stable prices (Accuracy) more than fluctuating prices.

**Comment by FruitFace** [comment]
@UselessGuru Don't you technically want it at 0 if mining only to NiceHash since it is a PPS service.  You get the advantage of not having to ramp up or lose out, like in PPLNS pools, like MPH.  I guess the only disadvantage would be the time it takes to switch miners, if the switching occurs to rapidly, where you have the time it takes for mining to stop and start.  So maybe 1, then?

**Comment by UselessGuru** [comment]
> Don't you technically want it at 0 if mining only to NiceHash since it is a PPS service.

Probably yes. Maybe some else can confirm.

 I think a switch at pool level (to be included in the pool.ps1 files) could be used to signal -SwitchingPrevention for NH and the like.

**Comment by Lycerion** [comment]
I did see that, I was hoping for a bit more detail as far as what the percentage means. 

Thanks!
