### ISSUE TITLE
ccminerAlexis78

### ISSUE THREAD

**Issue by Nicheuji** [MultiPoolMiner/MultiPoolMiner#975]
Could you add this to MPM? It performs much better than CcminerTpruvot on Skein
(112 MH/s more on my GTX 1070)
https://github.com/nemosminer/ccminer-hcash/releases

**Comment by ChriscomIT** [comment]
Or even re-add the CCMiner-Palgin as it has the best performance on skein.

**Comment by UselessGuru** [comment]
> CCMiner-Palgin as it has the best performance on skein.

Is no longer publicly available.

**Comment by grantemsley** [comment]
Turns out there may be a reason it had higher hashrates...but not be better

https://bitcointalk.org/index.php?topic=1907382.0;all

>> Quote from: djeZo on May 08, 2017, 08:53:31 PM
What you most likely did to achieve high speed is to make buckets smaller. This can of course greatly speed up everything, and displayed iterations are high, but on pool, you will get slow speed. These buckets sizes are there for a reason and not something you can simply shed off and benefit.
I also don't understand why would you have pool issues; equihash protocol is standardized, every pool works if it follows official zcash stratum specifications.
Also, we have released the source under GPL v3 and you are obligated to disclose full source when distributing the bins...

>Yes, you're right, that's exactly what I've done and found that won't work the right way, I'm still learning and practicing my skills, sorry for practicing on your work, which is highly appreciated by me. I've already removed the bins, think it's time to try to write my own kernels from the scratch, SKL and MKL versions.

**Comment by Nicheuji** [comment]
After doing some short observations through https://miningpoolhubstats.com/ I can confirm that the ccminerAlexis78 from nemosminer github performs better than CcminerTpruvot.
Please let me know if miningpoolhubstats isn't accurate or if you know other more accurate means of reading hashrates.

**Comment by TVanAusdall** [comment]
I started to go through adding ccminerAlexis78 to find out that it is already part of MPM. It is there as NVIDIA-Hsr...

**Comment by Nicheuji** [comment]
@UselessGuru Any plans on adding this?

**Comment by aaronsace** [comment]
https://github.com/MultiPoolMiner/MultiPoolMiner/blob/1f46e26643b98a74ab0f0eb2cacbe6fc7f143f33/Miners/CcminerHsr.ps1

**Comment by Nicheuji** [comment]
@aaronsace Thanks! Sorry, I overlooked that.
I'll close this then.
