### ISSUE TITLE
Idea: Optimizing NiceHash mining

### ISSUE THREAD

**Issue by UselessGuru** [MultiPoolMiner/MultiPoolMiner#979]
To my understanding NH is the only pool where always jumping on the fastest algo really makes sense.

True?

If so how could we achieve exactly this?

How about creating profitability stats that will always reflect a 100% accuracy. Would this make sense?

**Comment by aaronsace** [comment]
More factors would need adding to the accuracy; it doesn't function correctly if set to 100%.

**Comment by UselessGuru** [comment]
> it doesn't function correctly if set to 100%.

Too bad :-(

**Comment by UselessGuru** [comment]
What about setting SwitchingPrevention for PPS pools to 0?

To my understanding different pools use [different payout strategies](https://en.bitcoin.it/wiki/Comparison_of_mining_pools)

Would it make sense to add the payment type, e.g 'PPS' to the pool object?
This attribute could then be used to get the best miner like:
if pool.paymenttype = PPS SwitchingPrevention=0

**Comment by FruitFace** [comment]
@UselessGuru Check out my last response in issue #991 .Since I only mine to NiceHash, it's as close as I can get.  I do have MPH as my only backup, but I haven't fallen back to that as of yet, since NH came back.  I used to mine to Zpool, when NH was down, but now that I mine to the internal wallet, I can't use the same wallet in the config, for zpool, so MPH is the only backup that makes sense for me now.

**Comment by UselessGuru** [comment]
The latest commits allow extra parameters per pool to be configured in 'config.txt'

What about making the 'SwitchingPrevention' parameter a pool config parameter? NH could then be run with SwithingPrevention=0 so it always mines on the highest paying algorithm.

**Comment by UselessGuru** [comment]
This will be implemented in 3.1.0 Beta 7
- Added PayoutScheme property to pools (PPLNS & PPS)
SwitchingPrevention=1 (always use if best paying) will be applied to PPS pools (currently Nicehash only)
