### ISSUE TITLE
Volatile hashrates

### ISSUE THREAD

**Issue by ivivaj** [MultiPoolMiner/MultiPoolMiner#980]
Hello. I'm new to mining and i've been getting unconsistent, volatile hashrates. Any idea on how to solve it?  Also estimations on BTC/Day are not even close to real, maybe because of the former problem. Screenshot attached.

![untitle1d](https://user-images.githubusercontent.com/35225822/34673117-7148402e-f481-11e7-846e-70b08e91383a.png)

**Comment by UselessGuru** [comment]
Your screenshot says it all: Pool closed connection... 
Slightly fluctuating rates are normal. What you see is a drop off because the pool cannot be contacted.

BTW: Accuracy does NOT indicated fluctuating has rates, much more it reflects price stability reported by the pool

> Also estimations on BTC/Day are not even close to real

That is normal as written here, e.g.:
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/905
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/894
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/841
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/695

Please close if you are happy with the solution.

**Comment by ivivaj** [comment]
Alright,
