### ISSUE TITLE
I'm done with MPM. Takes forever to switch to most profitable.

### ISSUE THREAD

**Issue by thericeking** [MultiPoolMiner/MultiPoolMiner#986]
For some reason this miner is obsess with Skein when there are other more profitable coins. I understand is not design to switch right away until it's done but this thing just stays on that !@##$ coin all the time.

**Comment by UselessGuru** [comment]
May be you have broken skein stats. What may help:

- Download the lastest CcminerSP.ps1 (this fixes an issue with API not always being available)
- Set SwitchingPrevention to 1 or 2 (DO NOT set it 0)
- Stop MPM
- Delete all files in stats matching *_skein*.*
- Restart MPM it will re-bench Skein

**Comment by thericeking** [comment]
@UselessGuru I just recently re-bench both machines and I ALWAYS run the "RemoveLogs", "ResetProfit" and "ResetBenchmark" then I do a fresh reboot before running a new benchmark. Since you added the switch prevention feature I always left it at default 2. Where can I find information about SwitchPrevention? Documentation for MPM is still hard to come by. There's nothing on https://multipoolminer.io/docs that explains what it does. The word SwitchPrevention is not even there.

**Comment by UselessGuru** [comment]
If you don't want to mine Skein then remove it from the list of algos.
Or the very hard way: disable it in every miner file.

I cannot assist you further - you seem to be the only one with this issue.

**Comment by thericeking** [comment]
@UselessGuru So you are not going to explain what SwitchPrevention is? I understand what the word means. Switch Prevention. But how does exactly work. What does setting to 0, 1,2 does? You can't tell me how to set the miner to switch to most profitable coin instead of getting stuck for ours on the same !@#$ coin? I don't have a problem with mining Skein if is most profitable. I have a problem with this miner obsession with it and not switching to most profitable. I'm the only one with this problem? I have seen tons of post here of people having the same problem with this miner not switching to most profitable.

**Comment by thericeking** [comment]
If downloading the lastest CcminerSP.ps1 fixes an issue with API not always being available then why isn't there a new MPM release with this new fix? Seems kind of important to me that I'm losing money if this thing isn't working right.

**Comment by hiewliwen** [comment]
The SwitchingPrevention is explained here #877

**Comment by thericeking** [comment]
@hiewliwen Thanks for that. Why is it buried there instead of the official documentation page? How were you able to find this? Where is this search box I can type in keywords to find old discussions with important documentation that should be easily found in the main website official documentation.

**Comment by hiewliwen** [comment]
remove the filters from the search box, type "switching prevention".

**Comment by thericeking** [comment]
I just read the SwitchingPrevention is explained here #877 and I am still more confuse now than before on how it works. I'm so frustrated with you smart people and your math. Can we get a more simple explanation?

**Comment by UselessGuru** [comment]
The following is not an exact mathematical description, but it basically captures the 'magic inside MPM'

MPM checks prices on every loop.
Based on this it creates its internal fluctuation value per algo and pool. 
The more stable the prince infoo received by the pool the lower this this number (aaronsace: correct me if I'm wrong). 
Upon calculation for the best miner MPM multiples flutuation value ** SwitchingPrevention.
The result is then applied to the price received by the pool and result in the 'profit bias'.
The miner with the highest bias will be run.

**Comment by papacheal** [comment]
@thericeking Let's see if I can turn that frown upside-down: here is my "simplified" version of on the MPM logic for switching. It's a bit of a essay/read, but hopefully more "readable" that the more technical explanations you've seen before. Note that the "switchingprevention" logic has always been in MPM and was set at a value of 1: @aaronsace has just recently exposed this as a variable users can adjust, should they desire to tune MPM further.

First some general overview:

- The various pools estimated profit values (visible on their respective web pages) are determined by the pools themselves. Each algorithm estimated profit value is a combination of the current mined coin's last known exchange value in BTC, that coins network difficulty and the current pools overall hashrate. 
- Some pools only mine one coin per algorithm (e.g. miningpoolhubcoins), whereas other pools will automatically switch which coin is being actively mined for a particular algorithm based on that coins estimated profit (e.g. miningpoolhub). Generally, you would only want to mine a single coin (e.g. miningpoolhubcoins) if you intended to keep any mined coins as-is and do your own exchange work later.
- MPM polls all pools it knows about (enabled or not) on a pre-defined interval (default is every 60 seconds) to gather the pools estimated profit for all of its advertised algorithms. As these profits change at each polling interval (based on the three factors mentioned above), MPM tracks how often and how drastic the changes are per algorithm and records this per-algorithm as a "fluctuation" metric. This fluctuation or margin-of-error is represented in MPM's output as "accuracy". e.g. An algorithm whose reported estimated profit values have a 90% accuracy can be conversely thought of as having a 10% margin-of-error.
- As MPM repeatedly polls the pools over time, the more correct the reported accuracy (i.e. margin of error) becomes for a particular pools algorithm.
- Due to the nature of pool-based mining, it is generally considered better to mine longer on algorithms that are most profitable with low margin-of-error over time (i.e. high accuracy). Technically (and you can tune out for this, if you don't care), this takes into account concepts like PPLNS vs. PPS, ramp-up time for reported pool hash rate vs. miner reported hash rates, new/cheap coins with wildly fluctuating exchange prices etc.

Now for the switching (or anti-switching) logic:

1. MPM retrieves the estimated profit for all pools/algorithms and filters out any undesired algorithms.
2. The estimated profit for each pool/algorithm combo is reduced by a calculated percentage amount (see below for specifics) to determine a "biased" estimated profit.
3. The "biased" estimated profits for each enabled pool/algorithm are combined with the benchmark hashrates previously calculated for all miners to calculate potential profit for your specific rig.
4. The most profitable miner/algorithm/pool combination for your rig is selected and (if it isn't already running) it is launched.
5. MPM idles for a pre-defined interval of time (default 60 seconds), then repeats the steps above.

Determination of "biased" estimated profit:

The percentage amount that a reported estimated profit value is reduced is based on the calculation below (simplified for readability):

Percent Estimated Profit Reduction = (Margin of Error * SwitchingPrevention) / (Value that grows exponentially based on the number of minutes current miner has been running)

This means that the longer the current miner is running, the less MPM takes the Margin of Error into consideration and the less it reduces the estimated profit value. By adjusting the SwitchingPrevention value up, you increase the effect the Margin of Error has on the calculation and, therefore, increase the amount of current miner run-time required to reduce this effect.

In practice, this explains why when you first launch MPM it may pick a pool/algorithm combo that has a lower value in the "Currency/Day" column, as it is favoring a more accurate combo. Over time, assuming the more profitable pool/algorithm stays more profitable ,the accuracy will have less and less weight in the miner selection calculation process until MPM eventually switches over to it.

Obviously, a new install of MPM (or after someone runs ResetProfit on their existing install) has no historical information on which to build accurate "margin-of-error" values. MPM will, therefore, sometimes make less desirable miner selections and switch more often until it can gather enough info to stabilize its decision-making process.

Whew. Hope this helps!

**Comment by aaronsace** [comment]
@papacheal It's a relief to finally have someone understand it and articulate better than I ever could.

**Comment by aaronsace** [comment]
@fonyo Maybe this will help you with the docs.

**Comment by papacheal** [comment]
@aaronsace No worries; glad to help remove whatever confusion I can surrounding this masterpiece. I half-wondered if adding a "Biased" ("Expected"/"Estimated","Projected" ?) Currency/Day column would help reduce concerns about the switching decisions or just create more questions. That way users could see how the miners shift position over time, gradually creeping up to #1.

**Comment by fonyo** [comment]
Awesome explanation, @papacheal!! I will definitely add this and more. :) 👍 

As I mentioned on reddit as well, the real problem is people ARE EXPECTING an answer that is NOT LONGER than 3 sentences (and not only for switchingprevention but the entire logic of MPM).

I have already started preparing a logic explanation and graph for pools and how the whole thing comes together but unsure whether it is not going to be obsolete within the next couple of releases.

Regardless of all the above, thank you for this, @papacheal! Will be added tomorrow. 

@all Sorry, I have been very busy in the last two weeks and holding the front on the reddit and trying to keep things tidy here daily are all I could do lately.

**Comment by fonyo** [comment]
Added to the README.

**Comment by platinum4** [comment]
This was a complaint and is not a problem with the codebase; this is a preference held by the issue opener which may now be closed as it has been addressed in the Readme.
